/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.2
 *
 * This file is not intended to be easily readable and contains a number of
 * coding conventions designed to improve portability and efficiency. Do not make
 * changes to this file unless you know what you are doing--modify the SWIG
 * interface file instead.
 * ----------------------------------------------------------------------------- */

// source: ffi/bindings/telio.i

package teliogo

/*
#define intgo swig_intgo
typedef void *swig_voidp;

#include <stdint.h>
#include "callbacks.h"


typedef int intgo;
typedef unsigned int uintgo;



typedef struct { char *p; intgo n; } _gostring_;
typedef struct { void* array; intgo len; intgo cap; } _goslice_;


typedef void* swig_type_1;
typedef void* swig_type_2;
typedef void* swig_type_3;
typedef void* swig_type_4;
typedef _gostring_ swig_type_5;
typedef _gostring_ swig_type_6;
typedef _gostring_ swig_type_7;
typedef _gostring_ swig_type_8;
typedef _gostring_ swig_type_9;
typedef _gostring_ swig_type_10;
typedef long long swig_type_11;
typedef _gostring_ swig_type_12;
typedef _gostring_ swig_type_13;
typedef _gostring_ swig_type_14;
typedef _gostring_ swig_type_15;
typedef _gostring_ swig_type_16;
typedef _gostring_ swig_type_17;
typedef _gostring_ swig_type_18;
typedef _gostring_ swig_type_19;
typedef _gostring_ swig_type_20;
typedef _gostring_ swig_type_21;
typedef _gostring_ swig_type_22;
typedef _gostring_ swig_type_23;
typedef _gostring_ swig_type_24;
typedef _gostring_ swig_type_25;
typedef _gostring_ swig_type_26;
typedef _gostring_ swig_type_27;
typedef _gostring_ swig_type_28;
typedef _gostring_ swig_type_29;
typedef _gostring_ swig_type_30;
extern void _wrap_Swig_free_teliogo_9a5d0d120faf5ade(uintptr_t arg1);
extern uintptr_t _wrap_Swig_malloc_teliogo_9a5d0d120faf5ade(swig_intgo arg1);
extern swig_intgo _wrap_TELIOADAPTERBORINGTUN_teliogo_9a5d0d120faf5ade(void);
extern swig_intgo _wrap_TELIOADAPTERLINUXNATIVETUN_teliogo_9a5d0d120faf5ade(void);
extern swig_intgo _wrap_TELIOADAPTERWIREGUARDGOTUN_teliogo_9a5d0d120faf5ade(void);
extern swig_intgo _wrap_TELIOADAPTERWINDOWSNATIVETUN_teliogo_9a5d0d120faf5ade(void);
extern swig_intgo _wrap_TELIOLOGCRITICAL_teliogo_9a5d0d120faf5ade(void);
extern swig_intgo _wrap_TELIOLOGERROR_teliogo_9a5d0d120faf5ade(void);
extern swig_intgo _wrap_TELIOLOGWARNING_teliogo_9a5d0d120faf5ade(void);
extern swig_intgo _wrap_TELIOLOGINFO_teliogo_9a5d0d120faf5ade(void);
extern swig_intgo _wrap_TELIOLOGDEBUG_teliogo_9a5d0d120faf5ade(void);
extern swig_intgo _wrap_TELIOLOGTRACE_teliogo_9a5d0d120faf5ade(void);
extern swig_intgo _wrap_TELIORESOK_teliogo_9a5d0d120faf5ade(void);
extern swig_intgo _wrap_TELIORESERROR_teliogo_9a5d0d120faf5ade(void);
extern swig_intgo _wrap_TELIORESINVALIDKEY_teliogo_9a5d0d120faf5ade(void);
extern swig_intgo _wrap_TELIORESBADCONFIG_teliogo_9a5d0d120faf5ade(void);
extern swig_intgo _wrap_TELIORESLOCKERROR_teliogo_9a5d0d120faf5ade(void);
extern swig_intgo _wrap_TELIORESINVALIDSTRING_teliogo_9a5d0d120faf5ade(void);
extern swig_intgo _wrap_TELIORESALREADYSTARTED_teliogo_9a5d0d120faf5ade(void);
extern void _wrap_TelioEventCb_Ctx_set_teliogo_9a5d0d120faf5ade(uintptr_t arg1, uintptr_t arg2);
extern uintptr_t _wrap_TelioEventCb_Ctx_get_teliogo_9a5d0d120faf5ade(uintptr_t arg1);
extern void _wrap_TelioEventCb_Cb_set_teliogo_9a5d0d120faf5ade(uintptr_t arg1, swig_type_1 arg2);
extern swig_type_2 _wrap_TelioEventCb_Cb_get_teliogo_9a5d0d120faf5ade(uintptr_t arg1);
extern uintptr_t _wrap_new_TelioEventCb_teliogo_9a5d0d120faf5ade(void);
extern void _wrap_delete_TelioEventCb_teliogo_9a5d0d120faf5ade(uintptr_t arg1);
extern void _wrap_TelioLoggerCb_Ctx_set_teliogo_9a5d0d120faf5ade(uintptr_t arg1, uintptr_t arg2);
extern uintptr_t _wrap_TelioLoggerCb_Ctx_get_teliogo_9a5d0d120faf5ade(uintptr_t arg1);
extern void _wrap_TelioLoggerCb_Cb_set_teliogo_9a5d0d120faf5ade(uintptr_t arg1, swig_type_3 arg2);
extern swig_type_4 _wrap_TelioLoggerCb_Cb_get_teliogo_9a5d0d120faf5ade(uintptr_t arg1);
extern uintptr_t _wrap_new_TelioLoggerCb_teliogo_9a5d0d120faf5ade(void);
extern void _wrap_delete_TelioLoggerCb_teliogo_9a5d0d120faf5ade(uintptr_t arg1);
extern swig_intgo _wrap_Telio_GetDefaultAdapter_teliogo_9a5d0d120faf5ade(void);
extern uintptr_t _wrap_new_Telio_teliogo_9a5d0d120faf5ade(swig_type_5 arg1, telio_event_cb arg2, swig_intgo arg3, telio_logger_cb arg4);
extern void _wrap_delete_Telio_teliogo_9a5d0d120faf5ade(uintptr_t arg1);
extern swig_intgo _wrap_Telio_Start_teliogo_9a5d0d120faf5ade(uintptr_t arg1, swig_type_6 arg2, swig_intgo arg3);
extern swig_intgo _wrap_Telio_StartNamed_teliogo_9a5d0d120faf5ade(uintptr_t arg1, swig_type_7 arg2, swig_intgo arg3, swig_type_8 arg4);
extern swig_intgo _wrap_Telio_StartWithTun_teliogo_9a5d0d120faf5ade(uintptr_t arg1, swig_type_9 arg2, swig_intgo arg3, swig_intgo arg4);
extern swig_intgo _wrap_Telio_EnableMagicDns_teliogo_9a5d0d120faf5ade(uintptr_t arg1, swig_type_10 arg2);
extern swig_intgo _wrap_Telio_DisableMagicDns_teliogo_9a5d0d120faf5ade(uintptr_t arg1);
extern swig_intgo _wrap_Telio_Stop_teliogo_9a5d0d120faf5ade(uintptr_t arg1);
extern swig_type_11 _wrap_Telio_GetAdapterLuid_teliogo_9a5d0d120faf5ade(uintptr_t arg1);
extern swig_intgo _wrap_Telio_SetPrivateKey_teliogo_9a5d0d120faf5ade(uintptr_t arg1, swig_type_12 arg2);
extern swig_type_13 _wrap_Telio_GetPrivateKey_teliogo_9a5d0d120faf5ade(uintptr_t arg1);
extern swig_intgo _wrap_Telio_SetFwmark_teliogo_9a5d0d120faf5ade(uintptr_t arg1, swig_intgo arg2);
extern swig_intgo _wrap_Telio_NotifyNetworkChange_teliogo_9a5d0d120faf5ade(uintptr_t arg1, swig_type_14 arg2);
extern swig_intgo _wrap_Telio_ConnectToExitNode_teliogo_9a5d0d120faf5ade(uintptr_t arg1, swig_type_15 arg2, swig_type_16 arg3, swig_type_17 arg4);
extern swig_intgo _wrap_Telio_ConnectToExitNodeWithId_teliogo_9a5d0d120faf5ade(uintptr_t arg1, swig_type_18 arg2, swig_type_19 arg3, swig_type_20 arg4, swig_type_21 arg5);
extern swig_intgo _wrap_Telio_DisconnectFromExitNode_teliogo_9a5d0d120faf5ade(uintptr_t arg1, swig_type_22 arg2);
extern swig_intgo _wrap_Telio_DisconnectFromExitNodes_teliogo_9a5d0d120faf5ade(uintptr_t arg1);
extern swig_intgo _wrap_Telio_SetMeshnet_teliogo_9a5d0d120faf5ade(uintptr_t arg1, swig_type_23 arg2);
extern swig_intgo _wrap_Telio_SetMeshnetOff_teliogo_9a5d0d120faf5ade(uintptr_t arg1);
extern swig_type_24 _wrap_Telio_GenerateSecretKey_teliogo_9a5d0d120faf5ade(uintptr_t arg1);
extern swig_type_25 _wrap_Telio_GeneratePublicKey_teliogo_9a5d0d120faf5ade(uintptr_t arg1, swig_type_26 arg2);
extern swig_type_27 _wrap_Telio_GetStatusMap_teliogo_9a5d0d120faf5ade(uintptr_t arg1);
extern swig_type_28 _wrap_Telio_GetLastError_teliogo_9a5d0d120faf5ade(uintptr_t arg1);
extern swig_type_29 _wrap_Telio_GetVersionTag_teliogo_9a5d0d120faf5ade(void);
extern swig_type_30 _wrap_Telio_GetCommitSha_teliogo_9a5d0d120faf5ade(void);
#undef intgo
*/
import "C"

import "unsafe"
import _ "runtime/cgo"
import "sync"


type _ unsafe.Pointer



var Swig_escape_always_false bool
var Swig_escape_val interface{}


type _swig_fnptr *byte
type _swig_memberptr *byte


type _ sync.Mutex


type swig_gostring struct { p uintptr; n int32 }
func swigCopyString(s string) string {
  p := *(*swig_gostring)(unsafe.Pointer(&s))
  r := string((*[0x7fffffff]byte)(unsafe.Pointer(p.p))[:p.n])
  Swig_free(p.p)
  return r
}

func Swig_free(arg1 uintptr) {
	_swig_i_0 := arg1
	C._wrap_Swig_free_teliogo_9a5d0d120faf5ade(C.uintptr_t(_swig_i_0))
}

func Swig_malloc(arg1 int) (_swig_ret uintptr) {
	var swig_r uintptr
	_swig_i_0 := arg1
	swig_r = (uintptr)(C._wrap_Swig_malloc_teliogo_9a5d0d120faf5ade(C.swig_intgo(_swig_i_0)))
	return swig_r
}

type Enum_SS_telio_adapter_type int
func _swig_getTELIOADAPTERBORINGTUN() (_swig_ret Enum_SS_telio_adapter_type) {
	var swig_r Enum_SS_telio_adapter_type
	swig_r = (Enum_SS_telio_adapter_type)(C._wrap_TELIOADAPTERBORINGTUN_teliogo_9a5d0d120faf5ade())
	return swig_r
}

var TELIOADAPTERBORINGTUN Enum_SS_telio_adapter_type = _swig_getTELIOADAPTERBORINGTUN()
func _swig_getTELIOADAPTERLINUXNATIVETUN() (_swig_ret Enum_SS_telio_adapter_type) {
	var swig_r Enum_SS_telio_adapter_type
	swig_r = (Enum_SS_telio_adapter_type)(C._wrap_TELIOADAPTERLINUXNATIVETUN_teliogo_9a5d0d120faf5ade())
	return swig_r
}

var TELIOADAPTERLINUXNATIVETUN Enum_SS_telio_adapter_type = _swig_getTELIOADAPTERLINUXNATIVETUN()
func _swig_getTELIOADAPTERWIREGUARDGOTUN() (_swig_ret Enum_SS_telio_adapter_type) {
	var swig_r Enum_SS_telio_adapter_type
	swig_r = (Enum_SS_telio_adapter_type)(C._wrap_TELIOADAPTERWIREGUARDGOTUN_teliogo_9a5d0d120faf5ade())
	return swig_r
}

var TELIOADAPTERWIREGUARDGOTUN Enum_SS_telio_adapter_type = _swig_getTELIOADAPTERWIREGUARDGOTUN()
func _swig_getTELIOADAPTERWINDOWSNATIVETUN() (_swig_ret Enum_SS_telio_adapter_type) {
	var swig_r Enum_SS_telio_adapter_type
	swig_r = (Enum_SS_telio_adapter_type)(C._wrap_TELIOADAPTERWINDOWSNATIVETUN_teliogo_9a5d0d120faf5ade())
	return swig_r
}

var TELIOADAPTERWINDOWSNATIVETUN Enum_SS_telio_adapter_type = _swig_getTELIOADAPTERWINDOWSNATIVETUN()
type Enum_SS_telio_log_level int
func _swig_getTELIOLOGCRITICAL() (_swig_ret Enum_SS_telio_log_level) {
	var swig_r Enum_SS_telio_log_level
	swig_r = (Enum_SS_telio_log_level)(C._wrap_TELIOLOGCRITICAL_teliogo_9a5d0d120faf5ade())
	return swig_r
}

var TELIOLOGCRITICAL Enum_SS_telio_log_level = _swig_getTELIOLOGCRITICAL()
func _swig_getTELIOLOGERROR() (_swig_ret Enum_SS_telio_log_level) {
	var swig_r Enum_SS_telio_log_level
	swig_r = (Enum_SS_telio_log_level)(C._wrap_TELIOLOGERROR_teliogo_9a5d0d120faf5ade())
	return swig_r
}

var TELIOLOGERROR Enum_SS_telio_log_level = _swig_getTELIOLOGERROR()
func _swig_getTELIOLOGWARNING() (_swig_ret Enum_SS_telio_log_level) {
	var swig_r Enum_SS_telio_log_level
	swig_r = (Enum_SS_telio_log_level)(C._wrap_TELIOLOGWARNING_teliogo_9a5d0d120faf5ade())
	return swig_r
}

var TELIOLOGWARNING Enum_SS_telio_log_level = _swig_getTELIOLOGWARNING()
func _swig_getTELIOLOGINFO() (_swig_ret Enum_SS_telio_log_level) {
	var swig_r Enum_SS_telio_log_level
	swig_r = (Enum_SS_telio_log_level)(C._wrap_TELIOLOGINFO_teliogo_9a5d0d120faf5ade())
	return swig_r
}

var TELIOLOGINFO Enum_SS_telio_log_level = _swig_getTELIOLOGINFO()
func _swig_getTELIOLOGDEBUG() (_swig_ret Enum_SS_telio_log_level) {
	var swig_r Enum_SS_telio_log_level
	swig_r = (Enum_SS_telio_log_level)(C._wrap_TELIOLOGDEBUG_teliogo_9a5d0d120faf5ade())
	return swig_r
}

var TELIOLOGDEBUG Enum_SS_telio_log_level = _swig_getTELIOLOGDEBUG()
func _swig_getTELIOLOGTRACE() (_swig_ret Enum_SS_telio_log_level) {
	var swig_r Enum_SS_telio_log_level
	swig_r = (Enum_SS_telio_log_level)(C._wrap_TELIOLOGTRACE_teliogo_9a5d0d120faf5ade())
	return swig_r
}

var TELIOLOGTRACE Enum_SS_telio_log_level = _swig_getTELIOLOGTRACE()
type Enum_SS_telio_result int
func _swig_getTELIORESOK() (_swig_ret Enum_SS_telio_result) {
	var swig_r Enum_SS_telio_result
	swig_r = (Enum_SS_telio_result)(C._wrap_TELIORESOK_teliogo_9a5d0d120faf5ade())
	return swig_r
}

var TELIORESOK Enum_SS_telio_result = _swig_getTELIORESOK()
func _swig_getTELIORESERROR() (_swig_ret Enum_SS_telio_result) {
	var swig_r Enum_SS_telio_result
	swig_r = (Enum_SS_telio_result)(C._wrap_TELIORESERROR_teliogo_9a5d0d120faf5ade())
	return swig_r
}

var TELIORESERROR Enum_SS_telio_result = _swig_getTELIORESERROR()
func _swig_getTELIORESINVALIDKEY() (_swig_ret Enum_SS_telio_result) {
	var swig_r Enum_SS_telio_result
	swig_r = (Enum_SS_telio_result)(C._wrap_TELIORESINVALIDKEY_teliogo_9a5d0d120faf5ade())
	return swig_r
}

var TELIORESINVALIDKEY Enum_SS_telio_result = _swig_getTELIORESINVALIDKEY()
func _swig_getTELIORESBADCONFIG() (_swig_ret Enum_SS_telio_result) {
	var swig_r Enum_SS_telio_result
	swig_r = (Enum_SS_telio_result)(C._wrap_TELIORESBADCONFIG_teliogo_9a5d0d120faf5ade())
	return swig_r
}

var TELIORESBADCONFIG Enum_SS_telio_result = _swig_getTELIORESBADCONFIG()
func _swig_getTELIORESLOCKERROR() (_swig_ret Enum_SS_telio_result) {
	var swig_r Enum_SS_telio_result
	swig_r = (Enum_SS_telio_result)(C._wrap_TELIORESLOCKERROR_teliogo_9a5d0d120faf5ade())
	return swig_r
}

var TELIORESLOCKERROR Enum_SS_telio_result = _swig_getTELIORESLOCKERROR()
func _swig_getTELIORESINVALIDSTRING() (_swig_ret Enum_SS_telio_result) {
	var swig_r Enum_SS_telio_result
	swig_r = (Enum_SS_telio_result)(C._wrap_TELIORESINVALIDSTRING_teliogo_9a5d0d120faf5ade())
	return swig_r
}

var TELIORESINVALIDSTRING Enum_SS_telio_result = _swig_getTELIORESINVALIDSTRING()
func _swig_getTELIORESALREADYSTARTED() (_swig_ret Enum_SS_telio_result) {
	var swig_r Enum_SS_telio_result
	swig_r = (Enum_SS_telio_result)(C._wrap_TELIORESALREADYSTARTED_teliogo_9a5d0d120faf5ade())
	return swig_r
}

var TELIORESALREADYSTARTED Enum_SS_telio_result = _swig_getTELIORESALREADYSTARTED()
type SwigcptrTelioEventCb uintptr

func (p SwigcptrTelioEventCb) Swigcptr() uintptr {
	return (uintptr)(p)
}

func (p SwigcptrTelioEventCb) SwigIsTelioEventCb() {
}

func (arg1 SwigcptrTelioEventCb) SetCtx(arg2 uintptr) {
	_swig_i_0 := arg1
	_swig_i_1 := arg2
	C._wrap_TelioEventCb_Ctx_set_teliogo_9a5d0d120faf5ade(C.uintptr_t(_swig_i_0), C.uintptr_t(_swig_i_1))
}

func (arg1 SwigcptrTelioEventCb) GetCtx() (_swig_ret uintptr) {
	var swig_r uintptr
	_swig_i_0 := arg1
	swig_r = (uintptr)(C._wrap_TelioEventCb_Ctx_get_teliogo_9a5d0d120faf5ade(C.uintptr_t(_swig_i_0)))
	return swig_r
}

func (arg1 SwigcptrTelioEventCb) SetCb(arg2 _swig_fnptr) {
	_swig_i_0 := arg1
	_swig_i_1 := arg2
	C._wrap_TelioEventCb_Cb_set_teliogo_9a5d0d120faf5ade(C.uintptr_t(_swig_i_0), C.swig_type_1(_swig_i_1))
}

func (arg1 SwigcptrTelioEventCb) GetCb() (_swig_ret _swig_fnptr) {
	var swig_r _swig_fnptr
	_swig_i_0 := arg1
	swig_r = (_swig_fnptr)(C._wrap_TelioEventCb_Cb_get_teliogo_9a5d0d120faf5ade(C.uintptr_t(_swig_i_0)))
	return swig_r
}

func NewTelioEventCb() (_swig_ret TelioEventCb) {
	var swig_r TelioEventCb
	swig_r = (TelioEventCb)(SwigcptrTelioEventCb(C._wrap_new_TelioEventCb_teliogo_9a5d0d120faf5ade()))
	return swig_r
}

func DeleteTelioEventCb(arg1 TelioEventCb) {
	_swig_i_0 := arg1.Swigcptr()
	C._wrap_delete_TelioEventCb_teliogo_9a5d0d120faf5ade(C.uintptr_t(_swig_i_0))
}

type TelioEventCb interface {
	Swigcptr() uintptr
	SwigIsTelioEventCb()
	SetCtx(arg2 uintptr)
	GetCtx() (_swig_ret uintptr)
	SetCb(arg2 _swig_fnptr)
	GetCb() (_swig_ret _swig_fnptr)
}

type SwigcptrTelioLoggerCb uintptr

func (p SwigcptrTelioLoggerCb) Swigcptr() uintptr {
	return (uintptr)(p)
}

func (p SwigcptrTelioLoggerCb) SwigIsTelioLoggerCb() {
}

func (arg1 SwigcptrTelioLoggerCb) SetCtx(arg2 uintptr) {
	_swig_i_0 := arg1
	_swig_i_1 := arg2
	C._wrap_TelioLoggerCb_Ctx_set_teliogo_9a5d0d120faf5ade(C.uintptr_t(_swig_i_0), C.uintptr_t(_swig_i_1))
}

func (arg1 SwigcptrTelioLoggerCb) GetCtx() (_swig_ret uintptr) {
	var swig_r uintptr
	_swig_i_0 := arg1
	swig_r = (uintptr)(C._wrap_TelioLoggerCb_Ctx_get_teliogo_9a5d0d120faf5ade(C.uintptr_t(_swig_i_0)))
	return swig_r
}

func (arg1 SwigcptrTelioLoggerCb) SetCb(arg2 _swig_fnptr) {
	_swig_i_0 := arg1
	_swig_i_1 := arg2
	C._wrap_TelioLoggerCb_Cb_set_teliogo_9a5d0d120faf5ade(C.uintptr_t(_swig_i_0), C.swig_type_3(_swig_i_1))
}

func (arg1 SwigcptrTelioLoggerCb) GetCb() (_swig_ret _swig_fnptr) {
	var swig_r _swig_fnptr
	_swig_i_0 := arg1
	swig_r = (_swig_fnptr)(C._wrap_TelioLoggerCb_Cb_get_teliogo_9a5d0d120faf5ade(C.uintptr_t(_swig_i_0)))
	return swig_r
}

func NewTelioLoggerCb() (_swig_ret TelioLoggerCb) {
	var swig_r TelioLoggerCb
	swig_r = (TelioLoggerCb)(SwigcptrTelioLoggerCb(C._wrap_new_TelioLoggerCb_teliogo_9a5d0d120faf5ade()))
	return swig_r
}

func DeleteTelioLoggerCb(arg1 TelioLoggerCb) {
	_swig_i_0 := arg1.Swigcptr()
	C._wrap_delete_TelioLoggerCb_teliogo_9a5d0d120faf5ade(C.uintptr_t(_swig_i_0))
}

type TelioLoggerCb interface {
	Swigcptr() uintptr
	SwigIsTelioLoggerCb()
	SetCtx(arg2 uintptr)
	GetCtx() (_swig_ret uintptr)
	SetCb(arg2 _swig_fnptr)
	GetCb() (_swig_ret _swig_fnptr)
}


var eventCallbacks = map[uintptr]func(string){}
var loggerCallbacks = map[uintptr]func(int, string){}
// Note: This can only ensure enough place for 8 callbacks
// Application can crash when creating more if these the last
// items on stack
// The real fix for this would be to avoid using pointers where not necessary. In this case - key to hashmap
var arbitraryValue = uint64(0)
var arbitraryAddress = uintptr(unsafe.Pointer(&arbitraryValue))

func maxEventCbIndex() uintptr {
        maxI := arbitraryAddress
        for i := range eventCallbacks {
                if i > maxI {
                        maxI = i
                }
        }
        return maxI
}

func maxLoggerCbIndex() uintptr {
        maxI := arbitraryAddress
        for i := range loggerCallbacks {
                if i > maxI {
                        maxI = i
                }
        }
        return maxI
}


//export call_telio_event_cb
func call_telio_event_cb(ctx uintptr, str *C.char) {
        if callback, ok := eventCallbacks[ctx]; ok {
                callback(C.GoString(str))
        }
}


//export call_telio_logger_cb
func call_telio_logger_cb(ctx uintptr, level C.int, str *C.char) {
        if callback, ok := loggerCallbacks[ctx]; ok {
                callback(int(level), C.GoString(str))
        }
}

type SwigcptrTelio uintptr

func (p SwigcptrTelio) Swigcptr() uintptr {
	return (uintptr)(p)
}

func (p SwigcptrTelio) SwigIsTelio() {
}

func TelioGetDefaultAdapter() (_swig_ret Enum_SS_telio_adapter_type) {
	var swig_r Enum_SS_telio_adapter_type
	swig_r = (Enum_SS_telio_adapter_type)(C._wrap_Telio_GetDefaultAdapter_teliogo_9a5d0d120faf5ade())
	return swig_r
}

func NewTelio(arg1 string, arg2 func(string), arg3 Enum_SS_telio_log_level, arg4 func(int, string)) (_swig_ret Telio) {
	var swig_r Telio
	_swig_i_0 := arg1
	var _swig_i_1 C.telio_event_cb
{
        index := maxEventCbIndex() + 1
        cb := C.telio_event_cb{
                ctx: unsafe.Pointer(index),
                cb: (C.telio_event_fn)(C.call_telio_event_cb),
        }
        eventCallbacks[index] = arg2
        _swig_i_1 = cb
}
	_swig_i_2 := arg3
	var _swig_i_3 C.telio_logger_cb
{
        index := maxLoggerCbIndex() + 1
        cb := C.telio_logger_cb{
                ctx: unsafe.Pointer(index),
                cb: (C.telio_logger_fn)(C.call_telio_logger_cb),
        }
        loggerCallbacks[index] = arg4
        _swig_i_3 = cb
}
	swig_r = (Telio)(SwigcptrTelio(C._wrap_new_Telio_teliogo_9a5d0d120faf5ade(*(*C.swig_type_5)(unsafe.Pointer(&_swig_i_0)), C.telio_event_cb(_swig_i_1), C.swig_intgo(_swig_i_2), C.telio_logger_cb(_swig_i_3))))
	if Swig_escape_always_false {
		Swig_escape_val = arg1
	}
	var swig_r_1 Telio
{
        if swig_r == SwigcptrTelio(0) {
                swig_r_1 = nil
        }

        swig_r_1 = swig_r
}
	return swig_r_1
}

func DeleteTelio(arg1 Telio) {
	_swig_i_0 := arg1.Swigcptr()
	C._wrap_delete_Telio_teliogo_9a5d0d120faf5ade(C.uintptr_t(_swig_i_0))
}

func (arg1 SwigcptrTelio) Start(arg2 string, arg3 Enum_SS_telio_adapter_type) (_swig_ret Enum_SS_telio_result) {
	var swig_r Enum_SS_telio_result
	_swig_i_0 := arg1
	_swig_i_1 := arg2
	_swig_i_2 := arg3
	swig_r = (Enum_SS_telio_result)(C._wrap_Telio_Start_teliogo_9a5d0d120faf5ade(C.uintptr_t(_swig_i_0), *(*C.swig_type_6)(unsafe.Pointer(&_swig_i_1)), C.swig_intgo(_swig_i_2)))
	if Swig_escape_always_false {
		Swig_escape_val = arg2
	}
	return swig_r
}

func (arg1 SwigcptrTelio) StartNamed(arg2 string, arg3 Enum_SS_telio_adapter_type, arg4 string) (_swig_ret Enum_SS_telio_result) {
	var swig_r Enum_SS_telio_result
	_swig_i_0 := arg1
	_swig_i_1 := arg2
	_swig_i_2 := arg3
	_swig_i_3 := arg4
	swig_r = (Enum_SS_telio_result)(C._wrap_Telio_StartNamed_teliogo_9a5d0d120faf5ade(C.uintptr_t(_swig_i_0), *(*C.swig_type_7)(unsafe.Pointer(&_swig_i_1)), C.swig_intgo(_swig_i_2), *(*C.swig_type_8)(unsafe.Pointer(&_swig_i_3))))
	if Swig_escape_always_false {
		Swig_escape_val = arg2
	}
	if Swig_escape_always_false {
		Swig_escape_val = arg4
	}
	return swig_r
}

func (arg1 SwigcptrTelio) StartWithTun(arg2 string, arg3 Enum_SS_telio_adapter_type, arg4 int) (_swig_ret Enum_SS_telio_result) {
	var swig_r Enum_SS_telio_result
	_swig_i_0 := arg1
	_swig_i_1 := arg2
	_swig_i_2 := arg3
	_swig_i_3 := arg4
	swig_r = (Enum_SS_telio_result)(C._wrap_Telio_StartWithTun_teliogo_9a5d0d120faf5ade(C.uintptr_t(_swig_i_0), *(*C.swig_type_9)(unsafe.Pointer(&_swig_i_1)), C.swig_intgo(_swig_i_2), C.swig_intgo(_swig_i_3)))
	if Swig_escape_always_false {
		Swig_escape_val = arg2
	}
	return swig_r
}

func (arg1 SwigcptrTelio) EnableMagicDns(arg2 string) (_swig_ret Enum_SS_telio_result) {
	var swig_r Enum_SS_telio_result
	_swig_i_0 := arg1
	_swig_i_1 := arg2
	swig_r = (Enum_SS_telio_result)(C._wrap_Telio_EnableMagicDns_teliogo_9a5d0d120faf5ade(C.uintptr_t(_swig_i_0), *(*C.swig_type_10)(unsafe.Pointer(&_swig_i_1))))
	if Swig_escape_always_false {
		Swig_escape_val = arg2
	}
	return swig_r
}

func (arg1 SwigcptrTelio) DisableMagicDns() (_swig_ret Enum_SS_telio_result) {
	var swig_r Enum_SS_telio_result
	_swig_i_0 := arg1
	swig_r = (Enum_SS_telio_result)(C._wrap_Telio_DisableMagicDns_teliogo_9a5d0d120faf5ade(C.uintptr_t(_swig_i_0)))
	return swig_r
}

func (arg1 SwigcptrTelio) Stop() (_swig_ret Enum_SS_telio_result) {
	var swig_r Enum_SS_telio_result
	_swig_i_0 := arg1
	swig_r = (Enum_SS_telio_result)(C._wrap_Telio_Stop_teliogo_9a5d0d120faf5ade(C.uintptr_t(_swig_i_0)))
	return swig_r
}

func (arg1 SwigcptrTelio) GetAdapterLuid() (_swig_ret uint64) {
	var swig_r uint64
	_swig_i_0 := arg1
	swig_r = (uint64)(C._wrap_Telio_GetAdapterLuid_teliogo_9a5d0d120faf5ade(C.uintptr_t(_swig_i_0)))
	return swig_r
}

func (arg1 SwigcptrTelio) SetPrivateKey(arg2 string) (_swig_ret Enum_SS_telio_result) {
	var swig_r Enum_SS_telio_result
	_swig_i_0 := arg1
	_swig_i_1 := arg2
	swig_r = (Enum_SS_telio_result)(C._wrap_Telio_SetPrivateKey_teliogo_9a5d0d120faf5ade(C.uintptr_t(_swig_i_0), *(*C.swig_type_12)(unsafe.Pointer(&_swig_i_1))))
	if Swig_escape_always_false {
		Swig_escape_val = arg2
	}
	return swig_r
}

func (arg1 SwigcptrTelio) GetPrivateKey() (_swig_ret string) {
	var swig_r string
	_swig_i_0 := arg1
	swig_r_p := C._wrap_Telio_GetPrivateKey_teliogo_9a5d0d120faf5ade(C.uintptr_t(_swig_i_0))
	swig_r = *(*string)(unsafe.Pointer(&swig_r_p))
	var swig_r_1 string
 swig_r_1 = swigCopyString(swig_r) 
	return swig_r_1
}

func (arg1 SwigcptrTelio) SetFwmark(arg2 uint) (_swig_ret Enum_SS_telio_result) {
	var swig_r Enum_SS_telio_result
	_swig_i_0 := arg1
	_swig_i_1 := arg2
	swig_r = (Enum_SS_telio_result)(C._wrap_Telio_SetFwmark_teliogo_9a5d0d120faf5ade(C.uintptr_t(_swig_i_0), C.swig_intgo(_swig_i_1)))
	return swig_r
}

func (arg1 SwigcptrTelio) NotifyNetworkChange(arg2 string) (_swig_ret Enum_SS_telio_result) {
	var swig_r Enum_SS_telio_result
	_swig_i_0 := arg1
	_swig_i_1 := arg2
	swig_r = (Enum_SS_telio_result)(C._wrap_Telio_NotifyNetworkChange_teliogo_9a5d0d120faf5ade(C.uintptr_t(_swig_i_0), *(*C.swig_type_14)(unsafe.Pointer(&_swig_i_1))))
	if Swig_escape_always_false {
		Swig_escape_val = arg2
	}
	return swig_r
}

func (arg1 SwigcptrTelio) ConnectToExitNode(arg2 string, arg3 string, arg4 string) (_swig_ret Enum_SS_telio_result) {
	var swig_r Enum_SS_telio_result
	_swig_i_0 := arg1
	_swig_i_1 := arg2
	_swig_i_2 := arg3
	_swig_i_3 := arg4
	swig_r = (Enum_SS_telio_result)(C._wrap_Telio_ConnectToExitNode_teliogo_9a5d0d120faf5ade(C.uintptr_t(_swig_i_0), *(*C.swig_type_15)(unsafe.Pointer(&_swig_i_1)), *(*C.swig_type_16)(unsafe.Pointer(&_swig_i_2)), *(*C.swig_type_17)(unsafe.Pointer(&_swig_i_3))))
	if Swig_escape_always_false {
		Swig_escape_val = arg2
	}
	if Swig_escape_always_false {
		Swig_escape_val = arg3
	}
	if Swig_escape_always_false {
		Swig_escape_val = arg4
	}
	return swig_r
}

func (arg1 SwigcptrTelio) ConnectToExitNodeWithId(arg2 string, arg3 string, arg4 string, arg5 string) (_swig_ret Enum_SS_telio_result) {
	var swig_r Enum_SS_telio_result
	_swig_i_0 := arg1
	_swig_i_1 := arg2
	_swig_i_2 := arg3
	_swig_i_3 := arg4
	_swig_i_4 := arg5
	swig_r = (Enum_SS_telio_result)(C._wrap_Telio_ConnectToExitNodeWithId_teliogo_9a5d0d120faf5ade(C.uintptr_t(_swig_i_0), *(*C.swig_type_18)(unsafe.Pointer(&_swig_i_1)), *(*C.swig_type_19)(unsafe.Pointer(&_swig_i_2)), *(*C.swig_type_20)(unsafe.Pointer(&_swig_i_3)), *(*C.swig_type_21)(unsafe.Pointer(&_swig_i_4))))
	if Swig_escape_always_false {
		Swig_escape_val = arg2
	}
	if Swig_escape_always_false {
		Swig_escape_val = arg3
	}
	if Swig_escape_always_false {
		Swig_escape_val = arg4
	}
	if Swig_escape_always_false {
		Swig_escape_val = arg5
	}
	return swig_r
}

func (arg1 SwigcptrTelio) DisconnectFromExitNode(arg2 string) (_swig_ret Enum_SS_telio_result) {
	var swig_r Enum_SS_telio_result
	_swig_i_0 := arg1
	_swig_i_1 := arg2
	swig_r = (Enum_SS_telio_result)(C._wrap_Telio_DisconnectFromExitNode_teliogo_9a5d0d120faf5ade(C.uintptr_t(_swig_i_0), *(*C.swig_type_22)(unsafe.Pointer(&_swig_i_1))))
	if Swig_escape_always_false {
		Swig_escape_val = arg2
	}
	return swig_r
}

func (arg1 SwigcptrTelio) DisconnectFromExitNodes() (_swig_ret Enum_SS_telio_result) {
	var swig_r Enum_SS_telio_result
	_swig_i_0 := arg1
	swig_r = (Enum_SS_telio_result)(C._wrap_Telio_DisconnectFromExitNodes_teliogo_9a5d0d120faf5ade(C.uintptr_t(_swig_i_0)))
	return swig_r
}

func (arg1 SwigcptrTelio) SetMeshnet(arg2 string) (_swig_ret Enum_SS_telio_result) {
	var swig_r Enum_SS_telio_result
	_swig_i_0 := arg1
	_swig_i_1 := arg2
	swig_r = (Enum_SS_telio_result)(C._wrap_Telio_SetMeshnet_teliogo_9a5d0d120faf5ade(C.uintptr_t(_swig_i_0), *(*C.swig_type_23)(unsafe.Pointer(&_swig_i_1))))
	if Swig_escape_always_false {
		Swig_escape_val = arg2
	}
	return swig_r
}

func (arg1 SwigcptrTelio) SetMeshnetOff() (_swig_ret Enum_SS_telio_result) {
	var swig_r Enum_SS_telio_result
	_swig_i_0 := arg1
	swig_r = (Enum_SS_telio_result)(C._wrap_Telio_SetMeshnetOff_teliogo_9a5d0d120faf5ade(C.uintptr_t(_swig_i_0)))
	return swig_r
}

func (arg1 SwigcptrTelio) GenerateSecretKey() (_swig_ret string) {
	var swig_r string
	_swig_i_0 := arg1
	swig_r_p := C._wrap_Telio_GenerateSecretKey_teliogo_9a5d0d120faf5ade(C.uintptr_t(_swig_i_0))
	swig_r = *(*string)(unsafe.Pointer(&swig_r_p))
	var swig_r_1 string
 swig_r_1 = swigCopyString(swig_r) 
	return swig_r_1
}

func (arg1 SwigcptrTelio) GeneratePublicKey(arg2 string) (_swig_ret string) {
	var swig_r string
	_swig_i_0 := arg1
	_swig_i_1 := arg2
	swig_r_p := C._wrap_Telio_GeneratePublicKey_teliogo_9a5d0d120faf5ade(C.uintptr_t(_swig_i_0), *(*C.swig_type_26)(unsafe.Pointer(&_swig_i_1)))
	swig_r = *(*string)(unsafe.Pointer(&swig_r_p))
	if Swig_escape_always_false {
		Swig_escape_val = arg2
	}
	var swig_r_1 string
 swig_r_1 = swigCopyString(swig_r) 
	return swig_r_1
}

func (arg1 SwigcptrTelio) GetStatusMap() (_swig_ret string) {
	var swig_r string
	_swig_i_0 := arg1
	swig_r_p := C._wrap_Telio_GetStatusMap_teliogo_9a5d0d120faf5ade(C.uintptr_t(_swig_i_0))
	swig_r = *(*string)(unsafe.Pointer(&swig_r_p))
	var swig_r_1 string
 swig_r_1 = swigCopyString(swig_r) 
	return swig_r_1
}

func (arg1 SwigcptrTelio) GetLastError() (_swig_ret string) {
	var swig_r string
	_swig_i_0 := arg1
	swig_r_p := C._wrap_Telio_GetLastError_teliogo_9a5d0d120faf5ade(C.uintptr_t(_swig_i_0))
	swig_r = *(*string)(unsafe.Pointer(&swig_r_p))
	var swig_r_1 string
 swig_r_1 = swigCopyString(swig_r) 
	return swig_r_1
}

func TelioGetVersionTag() (_swig_ret string) {
	var swig_r string
	swig_r_p := C._wrap_Telio_GetVersionTag_teliogo_9a5d0d120faf5ade()
	swig_r = *(*string)(unsafe.Pointer(&swig_r_p))
	var swig_r_1 string
 swig_r_1 = swigCopyString(swig_r) 
	return swig_r_1
}

func TelioGetCommitSha() (_swig_ret string) {
	var swig_r string
	swig_r_p := C._wrap_Telio_GetCommitSha_teliogo_9a5d0d120faf5ade()
	swig_r = *(*string)(unsafe.Pointer(&swig_r_p))
	var swig_r_1 string
 swig_r_1 = swigCopyString(swig_r) 
	return swig_r_1
}

type Telio interface {
	Swigcptr() uintptr
	SwigIsTelio()
	Start(arg2 string, arg3 Enum_SS_telio_adapter_type) (_swig_ret Enum_SS_telio_result)
	StartNamed(arg2 string, arg3 Enum_SS_telio_adapter_type, arg4 string) (_swig_ret Enum_SS_telio_result)
	StartWithTun(arg2 string, arg3 Enum_SS_telio_adapter_type, arg4 int) (_swig_ret Enum_SS_telio_result)
	EnableMagicDns(arg2 string) (_swig_ret Enum_SS_telio_result)
	DisableMagicDns() (_swig_ret Enum_SS_telio_result)
	Stop() (_swig_ret Enum_SS_telio_result)
	GetAdapterLuid() (_swig_ret uint64)
	SetPrivateKey(arg2 string) (_swig_ret Enum_SS_telio_result)
	GetPrivateKey() (_swig_ret string)
	SetFwmark(arg2 uint) (_swig_ret Enum_SS_telio_result)
	NotifyNetworkChange(arg2 string) (_swig_ret Enum_SS_telio_result)
	ConnectToExitNode(arg2 string, arg3 string, arg4 string) (_swig_ret Enum_SS_telio_result)
	ConnectToExitNodeWithId(arg2 string, arg3 string, arg4 string, arg5 string) (_swig_ret Enum_SS_telio_result)
	DisconnectFromExitNode(arg2 string) (_swig_ret Enum_SS_telio_result)
	DisconnectFromExitNodes() (_swig_ret Enum_SS_telio_result)
	SetMeshnet(arg2 string) (_swig_ret Enum_SS_telio_result)
	SetMeshnetOff() (_swig_ret Enum_SS_telio_result)
	GenerateSecretKey() (_swig_ret string)
	GeneratePublicKey(arg2 string) (_swig_ret string)
	GetStatusMap() (_swig_ret string)
	GetLastError() (_swig_ret string)
}


