[package]
name = "wg-go-rust-wrapper"
version = "1.0.0"
edition = "2021"
license = "GPL-3.0-only"
repository = "https://github.com/NordSecurity/libtelio"
publish = false

[dependencies]
libc = "0.2.99"

[build-dependencies]
cc = "1.0"
