[package]
name = "telio-starcast"
version = "0.1.0"
edition = "2021"
license = "GPL-3.0-only"
repository = "https://github.com/NordSecurity/libtelio"
publish = false

[features]
default = []
# Compile task crate for testing
test-util = []

[dependencies]
async-trait.workspace = true
boringtun.workspace = true
futures.workspace = true
ipnetwork.workspace = true
pnet_packet.workspace = true
thiserror.workspace = true
tokio = { workspace = true, features = ["rt", "net", "sync", "macros"] }
tracing.workspace = true

telio-crypto.workspace = true
telio-model.workspace = true
telio-sockets.workspace = true
telio-task.workspace = true
telio-utils.workspace = true

[dev-dependencies]
rand.workspace = true
rstest.workspace = true
sn_fake_clock.workspace = true

telio-utils = { workspace = true, features = ["sn_fake_clock"] }
