[toolchain]
channel = "1.64"
targets = [
    "aarch64-apple-darwin",
    "arm-linux-androideabi",
    "x86_64-apple-darwin",
    "x86_64-pc-windows-gnu",
    "x86_64-unknown-linux-gnu",
]
profile = "default"
