/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.2
 *
 * This file is not intended to be easily readable and contains a number of
 * coding conventions designed to improve portability and efficiency. Do not make
 * changes to this file unless you know what you are doing--modify the SWIG
 * interface file instead.
 * ----------------------------------------------------------------------------- */


#ifndef SWIGJAVA
#define SWIGJAVA
#endif


/* -----------------------------------------------------------------------------
 *  This section contains generic SWIG labels for method/variable
 *  declarations/attributes, and other compiler dependent labels.
 * ----------------------------------------------------------------------------- */

/* template workaround for compilers that cannot correctly implement the C++ standard */
#ifndef SWIGTEMPLATEDISAMBIGUATOR
# if defined(__SUNPRO_CC) && (__SUNPRO_CC <= 0x560)
#  define SWIGTEMPLATEDISAMBIGUATOR template
# elif defined(__HP_aCC)
/* Needed even with `aCC -AA' when `aCC -V' reports HP ANSI C++ B3910B A.03.55 */
/* If we find a maximum version that requires this, the test would be __HP_aCC <= 35500 for A.03.55 */
#  define SWIGTEMPLATEDISAMBIGUATOR template
# else
#  define SWIGTEMPLATEDISAMBIGUATOR
# endif
#endif

/* inline attribute */
#ifndef SWIGINLINE
# if defined(__cplusplus) || (defined(__GNUC__) && !defined(__STRICT_ANSI__))
#   define SWIGINLINE inline
# else
#   define SWIGINLINE
# endif
#endif

/* attribute recognised by some compilers to avoid 'unused' warnings */
#ifndef SWIGUNUSED
# if defined(__GNUC__)
#   if !(defined(__cplusplus)) || (__GNUC__ > 3 || (__GNUC__ == 3 && __GNUC_MINOR__ >= 4))
#     define SWIGUNUSED __attribute__ ((__unused__))
#   else
#     define SWIGUNUSED
#   endif
# elif defined(__ICC)
#   define SWIGUNUSED __attribute__ ((__unused__))
# else
#   define SWIGUNUSED
# endif
#endif

#ifndef SWIG_MSC_UNSUPPRESS_4505
# if defined(_MSC_VER)
#   pragma warning(disable : 4505) /* unreferenced local function has been removed */
# endif
#endif

#ifndef SWIGUNUSEDPARM
# ifdef __cplusplus
#   define SWIGUNUSEDPARM(p)
# else
#   define SWIGUNUSEDPARM(p) p SWIGUNUSED
# endif
#endif

/* internal SWIG method */
#ifndef SWIGINTERN
# define SWIGINTERN static SWIGUNUSED
#endif

/* internal inline SWIG method */
#ifndef SWIGINTERNINLINE
# define SWIGINTERNINLINE SWIGINTERN SWIGINLINE
#endif

/* exporting methods */
#if defined(__GNUC__)
#  if (__GNUC__ >= 4) || (__GNUC__ == 3 && __GNUC_MINOR__ >= 4)
#    ifndef GCC_HASCLASSVISIBILITY
#      define GCC_HASCLASSVISIBILITY
#    endif
#  endif
#endif

#ifndef SWIGEXPORT
# if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
#   if defined(STATIC_LINKED)
#     define SWIGEXPORT
#   else
#     define SWIGEXPORT __declspec(dllexport)
#   endif
# else
#   if defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
#     define SWIGEXPORT __attribute__ ((visibility("default")))
#   else
#     define SWIGEXPORT
#   endif
# endif
#endif

/* calling conventions for Windows */
#ifndef SWIGSTDCALL
# if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
#   define SWIGSTDCALL __stdcall
# else
#   define SWIGSTDCALL
# endif
#endif

/* Deal with Microsoft's attempt at deprecating C standard runtime functions */
#if !defined(SWIG_NO_CRT_SECURE_NO_DEPRECATE) && defined(_MSC_VER) && !defined(_CRT_SECURE_NO_DEPRECATE)
# define _CRT_SECURE_NO_DEPRECATE
#endif

/* Deal with Microsoft's attempt at deprecating methods in the standard C++ library */
#if !defined(SWIG_NO_SCL_SECURE_NO_DEPRECATE) && defined(_MSC_VER) && !defined(_SCL_SECURE_NO_DEPRECATE)
# define _SCL_SECURE_NO_DEPRECATE
#endif

/* Deal with Apple's deprecated 'AssertMacros.h' from Carbon-framework */
#if defined(__APPLE__) && !defined(__ASSERT_MACROS_DEFINE_VERSIONS_WITHOUT_UNDERSCORES)
# define __ASSERT_MACROS_DEFINE_VERSIONS_WITHOUT_UNDERSCORES 0
#endif

/* Intel's compiler complains if a variable which was never initialised is
 * cast to void, which is a common idiom which we use to indicate that we
 * are aware a variable isn't used.  So we just silence that warning.
 * See: https://github.com/swig/swig/issues/192 for more discussion.
 */
#ifdef __INTEL_COMPILER
# pragma warning disable 592
#endif


/* Fix for jlong on some versions of gcc on Windows */
#if defined(__GNUC__) && !defined(__INTEL_COMPILER)
  typedef long long __int64;
#endif

/* Fix for jlong on 64-bit x86 Solaris */
#if defined(__x86_64)
# ifdef _LP64
#   undef _LP64
# endif
#endif

#include <jni.h>
#include <stdlib.h>
#include <string.h>


/* Support for throwing Java exceptions */
typedef enum {
  SWIG_JavaOutOfMemoryError = 1,
  SWIG_JavaIOException,
  SWIG_JavaRuntimeException,
  SWIG_JavaIndexOutOfBoundsException,
  SWIG_JavaArithmeticException,
  SWIG_JavaIllegalArgumentException,
  SWIG_JavaNullPointerException,
  SWIG_JavaDirectorPureVirtual,
  SWIG_JavaUnknownError,
  SWIG_JavaIllegalStateException,
} SWIG_JavaExceptionCodes;

typedef struct {
  SWIG_JavaExceptionCodes code;
  const char *java_exception;
} SWIG_JavaExceptions_t;


static void SWIGUNUSED SWIG_JavaThrowException(JNIEnv *jenv, SWIG_JavaExceptionCodes code, const char *msg) {
  jclass excep;
  static const SWIG_JavaExceptions_t java_exceptions[] = {
    { SWIG_JavaOutOfMemoryError, "java/lang/OutOfMemoryError" },
    { SWIG_JavaIOException, "java/io/IOException" },
    { SWIG_JavaRuntimeException, "java/lang/RuntimeException" },
    { SWIG_JavaIndexOutOfBoundsException, "java/lang/IndexOutOfBoundsException" },
    { SWIG_JavaArithmeticException, "java/lang/ArithmeticException" },
    { SWIG_JavaIllegalArgumentException, "java/lang/IllegalArgumentException" },
    { SWIG_JavaNullPointerException, "java/lang/NullPointerException" },
    { SWIG_JavaDirectorPureVirtual, "java/lang/RuntimeException" },
    { SWIG_JavaUnknownError,  "java/lang/UnknownError" },
    { SWIG_JavaIllegalStateException, "java/lang/IllegalStateException" },
    { (SWIG_JavaExceptionCodes)0,  "java/lang/UnknownError" }
  };
  const SWIG_JavaExceptions_t *except_ptr = java_exceptions;

  while (except_ptr->code != code && except_ptr->code)
    except_ptr++;

  (*jenv)->ExceptionClear(jenv);
  excep = (*jenv)->FindClass(jenv, except_ptr->java_exception);
  if (excep)
    (*jenv)->ThrowNew(jenv, excep, msg);
}


/* Contract support */

#define SWIG_contract_assert(nullreturn, expr, msg) if (!(expr)) {SWIG_JavaThrowException(jenv, SWIG_JavaIllegalArgumentException, msg); return nullreturn; } else


#include "../../telio.h"


#include "jni_helper.h"
#define PKG "com/nordsec/telio/"
static JavaVM *jvm = NULL;


DECLARE_CACHED_CLASS(iTelioEventCb, PKG "ITelioEventCb");
DECLARE_CACHED_METHOD_ID(iTelioEventCb, iTelioEventCbeventHandleID, "eventHandle", "(Ljava/lang/String;)V");

static void telio_jni_call_event_cb(void *ctx, const char *str) {
    if (!jvm) {
        return;
    }
    JNIEnv *env = NULL;
    
    jint res = (*jvm)->GetEnv(jvm, (void**)&env, JNI_VERSION_1_6);
    int attached = 0;
    if (JNI_EDETACHED == res) {
        JavaVMAttachArgs args = {
            .version = JNI_VERSION_1_6,
            .name = NULL,
            .group = NULL,
        };

        if ((*jvm)->AttachCurrentThread(jvm, &env, (void*)&args)) {
            return;
        }
        attached = 1;
    } else if (JNI_OK != res) {
        return;
    }

    jmethodID handle = GET_CACHED_METHOD_ID(env, iTelioEventCbeventHandleID);
    RETURN_AND_THROW_IF_NULL(env, handle, "eventHandle method not found.");

    jstring jstr = (*env)->NewStringUTF(env, str);
    RETURN_AND_THROW_IF_NULL(env, jstr, "Event string is null.");

    (*env)->CallVoidMethod(env, (jobject)ctx, handle, jstr);
    (*env)->DeleteLocalRef(env, jstr);
    if (attached) {
        (*jvm)->DetachCurrentThread(jvm);
    }
}


DECLARE_CACHED_CLASS(telioLogLevel, PKG "TelioLogLevel");
DECLARE_CACHED_STATIC_FIELD_ID(telioLogLevel, jLogLevelCritical, "LOG_CRITICAL", "L" PKG "TelioLogLevel;");
DECLARE_CACHED_STATIC_FIELD_ID(telioLogLevel, jLogLevelError,    "LOG_ERROR", "L" PKG "TelioLogLevel;");
DECLARE_CACHED_STATIC_FIELD_ID(telioLogLevel, jLogLevelWarning,  "LOG_WARNING", "L" PKG "TelioLogLevel;");
DECLARE_CACHED_STATIC_FIELD_ID(telioLogLevel, jLogLevelInfo,     "LOG_INFO", "L" PKG "TelioLogLevel;");
DECLARE_CACHED_STATIC_FIELD_ID(telioLogLevel, jLogLevelDebug,    "LOG_DEBUG", "L" PKG "TelioLogLevel;");
DECLARE_CACHED_STATIC_FIELD_ID(telioLogLevel, jLogLevelTrace,    "LOG_TRACE", "L" PKG "TelioLogLevel;");


DECLARE_CACHED_CLASS(iTelioLoggerCb, PKG "ITelioLoggerCb");
DECLARE_CACHED_METHOD_ID(iTelioLoggerCb, iTelioLoggerCbloggerHandleID, "loggerHandle", "(L" PKG "TelioLogLevel;Ljava/lang/String;)V");

static void telio_jni_call_logger_cb(void *ctx, enum telio_log_level level, const char *str) {
    if (!jvm) {
        return;
    }

    JNIEnv *env = NULL;

    jint res = (*jvm)->GetEnv(jvm, (void**)&env, JNI_VERSION_1_6);
    int attached = 0;
    if (JNI_EDETACHED == res) {
        JavaVMAttachArgs args = {
            .version = JNI_VERSION_1_6,
            .name = NULL,
            .group = NULL,
        };

        if ((*jvm)->AttachCurrentThread(jvm, &env, (void*)&args)) {
            return;
        }
        attached = 1;
    } else if (JNI_OK != res) {
        return;
    }

    jmethodID handle = GET_CACHED_METHOD_ID(env, iTelioLoggerCbloggerHandleID);
    RETURN_AND_THROW_IF_NULL(env, handle, "loggerHandle not found.");

    jstring jstr = (*env)->NewStringUTF(env, str);
    RETURN_AND_THROW_IF_NULL(env, jstr, "Cannot crate log string.");

    jfieldID lfid = NULL;
    jclass jlevelClass = GET_CACHED_CLASS(env, telioLogLevel);
    RETURN_AND_THROW_IF_NULL(env, jlevelClass, "could not find TelioLogLevel class .");
    jobject jlevel = NULL;
    #define MAP(level, field) \
        case level:\
            lfid = GET_CACHED_STATIC_FIELD_ID(env, field);\
            RETURN_AND_THROW_IF_NULL(env, lfid, #level " level class not found.")\
            jlevel = (*env)->GetStaticObjectField(env, jlevelClass, lfid);\
            RETURN_AND_THROW_IF_NULL(env, jlevel, #level " level class not found.")\
            break;
    switch (level) {
        MAP(TELIO_LOG_CRITICAL, jLogLevelCritical)
        MAP(TELIO_LOG_ERROR, jLogLevelError)
        MAP(TELIO_LOG_WARNING, jLogLevelWarning)
        MAP(TELIO_LOG_INFO, jLogLevelInfo)
        MAP(TELIO_LOG_DEBUG, jLogLevelDebug)
        MAP(TELIO_LOG_TRACE, jLogLevelTrace)
    }
    #undef MAP

    (*env)->CallVoidMethod(env, (jobject)ctx, handle, jlevel, jstr);
    (*env)->DeleteLocalRef(env, jlevel);
    (*env)->DeleteLocalRef(env, jstr);
    if (attached) {
        (*jvm)->DetachCurrentThread(jvm);
    }
}


DECLARE_CACHED_CLASS(iTelioProtectCb, PKG "ITelioProtectCb");
DECLARE_CACHED_METHOD_ID(iTelioProtectCb, iTelioProtectCbprotectHandleID, "protectHandle", "(I)V");

static void telio_jni_call_protect_cb(void *ctx, int fd) {
    if (!jvm) {
        return;
    }
    JNIEnv *env = NULL;
    
    jint res = (*jvm)->GetEnv(jvm, (void**)&env, JNI_VERSION_1_6);
    int attached = 0;
    if (JNI_EDETACHED == res) {
        JavaVMAttachArgs args = {
            .version = JNI_VERSION_1_6,
            .name = NULL,
            .group = NULL,
        };

        if ((*jvm)->AttachCurrentThread(jvm, &env, (void*)&args)) {
            return;
        }
        attached = 1;
    } else if (JNI_OK != res) {
        return;
    }

    jmethodID handle = GET_CACHED_METHOD_ID(env, iTelioProtectCbprotectHandleID);
    RETURN_AND_THROW_IF_NULL(env, handle, "eventHandle method not found.");

    (*env)->CallVoidMethod(env, (jobject)ctx, handle, fd);

    if (attached) {
        (*jvm)->DetachCurrentThread(jvm);
    }
}


jint JNI_OnLoad(JavaVM *jvm, void *reserved) {
    JNIEnv *env = NULL;
    jint res = (*jvm)->GetEnv(jvm, (void**)&env, JNI_VERSION_1_6);

    // FindClass will be called by a background thread, and it's not guaranteed that a non-main thread will find the class in question.
    // To ensure that class and method reference is cached, the first lookup is performed during jni initialization (by the main thread)
    GET_CACHED_METHOD_ID(env, iTelioLoggerCbloggerHandleID);
    GET_CACHED_METHOD_ID(env, iTelioEventCbeventHandleID);
    GET_CACHED_METHOD_ID(env, iTelioProtectCbprotectHandleID);
    GET_CACHED_CLASS(env, telioLogLevel);

    return JNI_VERSION_1_6;
}

SWIGINTERN struct telio *new_telio(char const *features,telio_event_cb events,enum telio_log_level level,telio_logger_cb logger,telio_protect_cb protect,jobject ctx){
        telio *t;
        JNIEnv *env = NULL;
        if ((*jvm)->GetEnv(jvm, (void**)&env, JNI_VERSION_1_6)) {
            exit(1);
        }

        telio_init_cert_store(env, ctx);

        enum telio_result result;
        if ((result = telio_new_with_protect(&t, features, events, level, logger, protect)) != TELIO_RES_OK) {
            SWIG_JavaThrowException(env, SWIG_JavaIllegalArgumentException, "Failed to initiate telio");
            return NULL;
        }

        return t;
    }
SWIGINTERN void delete_telio(struct telio *self){
        telio_destroy(self);
    }

#ifdef __cplusplus
extern "C" {
#endif

SWIGEXPORT jint JNICALL Java_com_nordsec_telio_libtelioJNI_LOG_1CRITICAL_1get(JNIEnv *jenv, jclass jcls) {
  jint jresult = 0 ;
  enum telio_log_level result;
  
  (void)jenv;
  (void)jcls;
  result = (enum telio_log_level)TELIO_LOG_CRITICAL;
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT jint JNICALL Java_com_nordsec_telio_libtelioJNI_LOG_1ERROR_1get(JNIEnv *jenv, jclass jcls) {
  jint jresult = 0 ;
  enum telio_log_level result;
  
  (void)jenv;
  (void)jcls;
  result = (enum telio_log_level)TELIO_LOG_ERROR;
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT jint JNICALL Java_com_nordsec_telio_libtelioJNI_LOG_1WARNING_1get(JNIEnv *jenv, jclass jcls) {
  jint jresult = 0 ;
  enum telio_log_level result;
  
  (void)jenv;
  (void)jcls;
  result = (enum telio_log_level)TELIO_LOG_WARNING;
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT jint JNICALL Java_com_nordsec_telio_libtelioJNI_LOG_1INFO_1get(JNIEnv *jenv, jclass jcls) {
  jint jresult = 0 ;
  enum telio_log_level result;
  
  (void)jenv;
  (void)jcls;
  result = (enum telio_log_level)TELIO_LOG_INFO;
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT jint JNICALL Java_com_nordsec_telio_libtelioJNI_LOG_1DEBUG_1get(JNIEnv *jenv, jclass jcls) {
  jint jresult = 0 ;
  enum telio_log_level result;
  
  (void)jenv;
  (void)jcls;
  result = (enum telio_log_level)TELIO_LOG_DEBUG;
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT jint JNICALL Java_com_nordsec_telio_libtelioJNI_LOG_1TRACE_1get(JNIEnv *jenv, jclass jcls) {
  jint jresult = 0 ;
  enum telio_log_level result;
  
  (void)jenv;
  (void)jcls;
  result = (enum telio_log_level)TELIO_LOG_TRACE;
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT jint JNICALL Java_com_nordsec_telio_libtelioJNI_RES_1OK_1get(JNIEnv *jenv, jclass jcls) {
  jint jresult = 0 ;
  enum telio_result result;
  
  (void)jenv;
  (void)jcls;
  result = (enum telio_result)TELIO_RES_OK;
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT jint JNICALL Java_com_nordsec_telio_libtelioJNI_RES_1ERROR_1get(JNIEnv *jenv, jclass jcls) {
  jint jresult = 0 ;
  enum telio_result result;
  
  (void)jenv;
  (void)jcls;
  result = (enum telio_result)TELIO_RES_ERROR;
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT jint JNICALL Java_com_nordsec_telio_libtelioJNI_RES_1INVALID_1KEY_1get(JNIEnv *jenv, jclass jcls) {
  jint jresult = 0 ;
  enum telio_result result;
  
  (void)jenv;
  (void)jcls;
  result = (enum telio_result)TELIO_RES_INVALID_KEY;
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT jint JNICALL Java_com_nordsec_telio_libtelioJNI_RES_1BAD_1CONFIG_1get(JNIEnv *jenv, jclass jcls) {
  jint jresult = 0 ;
  enum telio_result result;
  
  (void)jenv;
  (void)jcls;
  result = (enum telio_result)TELIO_RES_BAD_CONFIG;
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT jint JNICALL Java_com_nordsec_telio_libtelioJNI_RES_1LOCK_1ERROR_1get(JNIEnv *jenv, jclass jcls) {
  jint jresult = 0 ;
  enum telio_result result;
  
  (void)jenv;
  (void)jcls;
  result = (enum telio_result)TELIO_RES_LOCK_ERROR;
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT jint JNICALL Java_com_nordsec_telio_libtelioJNI_RES_1INVALID_1STRING_1get(JNIEnv *jenv, jclass jcls) {
  jint jresult = 0 ;
  enum telio_result result;
  
  (void)jenv;
  (void)jcls;
  result = (enum telio_result)TELIO_RES_INVALID_STRING;
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT jint JNICALL Java_com_nordsec_telio_libtelioJNI_RES_1ALREADY_1STARTED_1get(JNIEnv *jenv, jclass jcls) {
  jint jresult = 0 ;
  enum telio_result result;
  
  (void)jenv;
  (void)jcls;
  result = (enum telio_result)TELIO_RES_ALREADY_STARTED;
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT jlong JNICALL Java_com_nordsec_telio_libtelioJNI_new_1Telio(JNIEnv *jenv, jclass jcls, jstring jarg1, jobject jarg2, jint jarg3, jobject jarg4, jobject jarg5, jobject jarg6) {
  jlong jresult = 0 ;
  char *arg1 = (char *) 0 ;
  telio_event_cb arg2 ;
  enum telio_log_level arg3 ;
  telio_logger_cb arg4 ;
  telio_protect_cb arg5 ;
  jobject arg6 ;
  struct telio *result = 0 ;
  
  (void)jenv;
  (void)jcls;
  arg1 = 0;
  if (jarg1) {
    arg1 = (char *)(*jenv)->GetStringUTFChars(jenv, jarg1, 0);
    if (!arg1) return 0;
  }
  {
    if (!jvm) {
      (*jenv)->GetJavaVM(jenv, &jvm);
    }
    
    telio_event_cb cb = {
      .ctx = (*jenv)->NewGlobalRef(jenv, jarg2),
      .cb = telio_jni_call_event_cb,
    };
    
    arg2 = cb;
  }
  arg3 = (enum telio_log_level)jarg3; 
  {
    if (!jvm) {
      (*jenv)->GetJavaVM(jenv, &jvm);
    }
    telio_logger_cb cb = {
      .ctx = (*jenv)->NewGlobalRef(jenv, jarg4),
      .cb = telio_jni_call_logger_cb,
    };
    arg4 = cb;
  }
  {
    if (!jvm) {
      (*jenv)->GetJavaVM(jenv, &jvm);
    }
    telio_protect_cb cb = {
      .ctx = (*jenv)->NewGlobalRef(jenv, jarg5),
      .cb = telio_jni_call_protect_cb,
    };
    arg5 = cb;
  }
  arg6 = jarg6; 
  result = (struct telio *)new_telio((char const *)arg1,arg2,arg3,arg4,arg5,arg6);
  *(struct telio **)&jresult = result; 
  if (arg1) (*jenv)->ReleaseStringUTFChars(jenv, jarg1, (const char *)arg1);
  return jresult;
}


SWIGEXPORT jint JNICALL Java_com_nordsec_telio_libtelioJNI_Telio_1getDefaultAdapter(JNIEnv *jenv, jclass jcls) {
  jint jresult = 0 ;
  enum telio_adapter_type result;
  
  (void)jenv;
  (void)jcls;
  result = (enum telio_adapter_type)telio_get_default_adapter();
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT void JNICALL Java_com_nordsec_telio_libtelioJNI_delete_1Telio(JNIEnv *jenv, jclass jcls, jlong jarg1) {
  struct telio *arg1 = (struct telio *) 0 ;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(struct telio **)&jarg1; 
  delete_telio(arg1);
}


SWIGEXPORT jint JNICALL Java_com_nordsec_telio_libtelioJNI_Telio_1start(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jstring jarg2, jint jarg3) {
  jint jresult = 0 ;
  struct telio *arg1 = (struct telio *) 0 ;
  char *arg2 = (char *) 0 ;
  enum telio_adapter_type arg3 ;
  enum telio_result result;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(struct telio **)&jarg1; 
  arg2 = 0;
  if (jarg2) {
    arg2 = (char *)(*jenv)->GetStringUTFChars(jenv, jarg2, 0);
    if (!arg2) return 0;
  }
  arg3 = (enum telio_adapter_type)jarg3; 
  result = (enum telio_result)telio_start(arg1,(char const *)arg2,arg3);
  jresult = (jint)result; 
  if (arg2) (*jenv)->ReleaseStringUTFChars(jenv, jarg2, (const char *)arg2);
  return jresult;
}


SWIGEXPORT jint JNICALL Java_com_nordsec_telio_libtelioJNI_Telio_1startNamed(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jstring jarg2, jint jarg3, jstring jarg4) {
  jint jresult = 0 ;
  struct telio *arg1 = (struct telio *) 0 ;
  char *arg2 = (char *) 0 ;
  enum telio_adapter_type arg3 ;
  char *arg4 = (char *) 0 ;
  enum telio_result result;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(struct telio **)&jarg1; 
  arg2 = 0;
  if (jarg2) {
    arg2 = (char *)(*jenv)->GetStringUTFChars(jenv, jarg2, 0);
    if (!arg2) return 0;
  }
  arg3 = (enum telio_adapter_type)jarg3; 
  arg4 = 0;
  if (jarg4) {
    arg4 = (char *)(*jenv)->GetStringUTFChars(jenv, jarg4, 0);
    if (!arg4) return 0;
  }
  result = (enum telio_result)telio_start_named(arg1,(char const *)arg2,arg3,(char const *)arg4);
  jresult = (jint)result; 
  if (arg2) (*jenv)->ReleaseStringUTFChars(jenv, jarg2, (const char *)arg2);
  if (arg4) (*jenv)->ReleaseStringUTFChars(jenv, jarg4, (const char *)arg4);
  return jresult;
}


SWIGEXPORT jint JNICALL Java_com_nordsec_telio_libtelioJNI_Telio_1startWithTun(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jstring jarg2, jint jarg3, jint jarg4) {
  jint jresult = 0 ;
  struct telio *arg1 = (struct telio *) 0 ;
  char *arg2 = (char *) 0 ;
  enum telio_adapter_type arg3 ;
  int arg4 ;
  enum telio_result result;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(struct telio **)&jarg1; 
  arg2 = 0;
  if (jarg2) {
    arg2 = (char *)(*jenv)->GetStringUTFChars(jenv, jarg2, 0);
    if (!arg2) return 0;
  }
  arg3 = (enum telio_adapter_type)jarg3; 
  arg4 = (int)jarg4; 
  result = (enum telio_result)telio_start_with_tun(arg1,(char const *)arg2,arg3,arg4);
  jresult = (jint)result; 
  if (arg2) (*jenv)->ReleaseStringUTFChars(jenv, jarg2, (const char *)arg2);
  return jresult;
}


SWIGEXPORT jint JNICALL Java_com_nordsec_telio_libtelioJNI_Telio_1enableMagicDns(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jstring jarg2) {
  jint jresult = 0 ;
  struct telio *arg1 = (struct telio *) 0 ;
  char *arg2 = (char *) 0 ;
  enum telio_result result;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(struct telio **)&jarg1; 
  arg2 = 0;
  if (jarg2) {
    arg2 = (char *)(*jenv)->GetStringUTFChars(jenv, jarg2, 0);
    if (!arg2) return 0;
  }
  result = (enum telio_result)telio_enable_magic_dns(arg1,(char const *)arg2);
  jresult = (jint)result; 
  if (arg2) (*jenv)->ReleaseStringUTFChars(jenv, jarg2, (const char *)arg2);
  return jresult;
}


SWIGEXPORT jint JNICALL Java_com_nordsec_telio_libtelioJNI_Telio_1disableMagicDns(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  jint jresult = 0 ;
  struct telio *arg1 = (struct telio *) 0 ;
  enum telio_result result;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(struct telio **)&jarg1; 
  result = (enum telio_result)telio_disable_magic_dns(arg1);
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT jint JNICALL Java_com_nordsec_telio_libtelioJNI_Telio_1stop(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  jint jresult = 0 ;
  struct telio *arg1 = (struct telio *) 0 ;
  enum telio_result result;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(struct telio **)&jarg1; 
  result = (enum telio_result)telio_stop(arg1);
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT jobject JNICALL Java_com_nordsec_telio_libtelioJNI_Telio_1getAdapterLuid(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  jobject jresult = 0 ;
  struct telio *arg1 = (struct telio *) 0 ;
  unsigned long long result;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(struct telio **)&jarg1; 
  result = (unsigned long long)telio_get_adapter_luid(arg1);
  {
    jbyteArray ba = (*jenv)->NewByteArray(jenv, 9);
    jbyte* bae = (*jenv)->GetByteArrayElements(jenv, ba, 0);
    jclass clazz = (*jenv)->FindClass(jenv, "java/math/BigInteger");
    jmethodID mid = (*jenv)->GetMethodID(jenv, clazz, "<init>", "([B)V");
    jobject bigint;
    int i;
    
    bae[0] = 0;
    for(i=1; i<9; i++ ) {
      bae[i] = (jbyte)(result>>8*(8-i));
    }
    
    (*jenv)->ReleaseByteArrayElements(jenv, ba, bae, 0);
    bigint = (*jenv)->NewObject(jenv, clazz, mid, ba);
    (*jenv)->DeleteLocalRef(jenv, ba);
    jresult = bigint;
  }
  return jresult;
}


SWIGEXPORT jint JNICALL Java_com_nordsec_telio_libtelioJNI_Telio_1setPrivateKey(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jstring jarg2) {
  jint jresult = 0 ;
  struct telio *arg1 = (struct telio *) 0 ;
  char *arg2 = (char *) 0 ;
  enum telio_result result;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(struct telio **)&jarg1; 
  arg2 = 0;
  if (jarg2) {
    arg2 = (char *)(*jenv)->GetStringUTFChars(jenv, jarg2, 0);
    if (!arg2) return 0;
  }
  result = (enum telio_result)telio_set_private_key(arg1,(char const *)arg2);
  jresult = (jint)result; 
  if (arg2) (*jenv)->ReleaseStringUTFChars(jenv, jarg2, (const char *)arg2);
  return jresult;
}


SWIGEXPORT jstring JNICALL Java_com_nordsec_telio_libtelioJNI_Telio_1getPrivateKey(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  jstring jresult = 0 ;
  struct telio *arg1 = (struct telio *) 0 ;
  char *result = 0 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(struct telio **)&jarg1; 
  result = (char *)telio_get_private_key(arg1);
  if (result) jresult = (*jenv)->NewStringUTF(jenv, (const char *)result);
  return jresult;
}


SWIGEXPORT jint JNICALL Java_com_nordsec_telio_libtelioJNI_Telio_1notifyNetworkChange(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jstring jarg2) {
  jint jresult = 0 ;
  struct telio *arg1 = (struct telio *) 0 ;
  char *arg2 = (char *) 0 ;
  enum telio_result result;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(struct telio **)&jarg1; 
  arg2 = 0;
  if (jarg2) {
    arg2 = (char *)(*jenv)->GetStringUTFChars(jenv, jarg2, 0);
    if (!arg2) return 0;
  }
  result = (enum telio_result)telio_notify_network_change(arg1,(char const *)arg2);
  jresult = (jint)result; 
  if (arg2) (*jenv)->ReleaseStringUTFChars(jenv, jarg2, (const char *)arg2);
  return jresult;
}


SWIGEXPORT jint JNICALL Java_com_nordsec_telio_libtelioJNI_Telio_1connectToExitNode(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jstring jarg2, jstring jarg3, jstring jarg4) {
  jint jresult = 0 ;
  struct telio *arg1 = (struct telio *) 0 ;
  char *arg2 = (char *) 0 ;
  char *arg3 = (char *) 0 ;
  char *arg4 = (char *) 0 ;
  enum telio_result result;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(struct telio **)&jarg1; 
  arg2 = 0;
  if (jarg2) {
    arg2 = (char *)(*jenv)->GetStringUTFChars(jenv, jarg2, 0);
    if (!arg2) return 0;
  }
  arg3 = 0;
  if (jarg3) {
    arg3 = (char *)(*jenv)->GetStringUTFChars(jenv, jarg3, 0);
    if (!arg3) return 0;
  }
  arg4 = 0;
  if (jarg4) {
    arg4 = (char *)(*jenv)->GetStringUTFChars(jenv, jarg4, 0);
    if (!arg4) return 0;
  }
  result = (enum telio_result)telio_connect_to_exit_node(arg1,(char const *)arg2,(char const *)arg3,(char const *)arg4);
  jresult = (jint)result; 
  if (arg2) (*jenv)->ReleaseStringUTFChars(jenv, jarg2, (const char *)arg2);
  if (arg3) (*jenv)->ReleaseStringUTFChars(jenv, jarg3, (const char *)arg3);
  if (arg4) (*jenv)->ReleaseStringUTFChars(jenv, jarg4, (const char *)arg4);
  return jresult;
}


SWIGEXPORT jint JNICALL Java_com_nordsec_telio_libtelioJNI_Telio_1connectToExitNodeWithId(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jstring jarg2, jstring jarg3, jstring jarg4, jstring jarg5) {
  jint jresult = 0 ;
  struct telio *arg1 = (struct telio *) 0 ;
  char *arg2 = (char *) 0 ;
  char *arg3 = (char *) 0 ;
  char *arg4 = (char *) 0 ;
  char *arg5 = (char *) 0 ;
  enum telio_result result;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(struct telio **)&jarg1; 
  arg2 = 0;
  if (jarg2) {
    arg2 = (char *)(*jenv)->GetStringUTFChars(jenv, jarg2, 0);
    if (!arg2) return 0;
  }
  arg3 = 0;
  if (jarg3) {
    arg3 = (char *)(*jenv)->GetStringUTFChars(jenv, jarg3, 0);
    if (!arg3) return 0;
  }
  arg4 = 0;
  if (jarg4) {
    arg4 = (char *)(*jenv)->GetStringUTFChars(jenv, jarg4, 0);
    if (!arg4) return 0;
  }
  arg5 = 0;
  if (jarg5) {
    arg5 = (char *)(*jenv)->GetStringUTFChars(jenv, jarg5, 0);
    if (!arg5) return 0;
  }
  result = (enum telio_result)telio_connect_to_exit_node_with_id(arg1,(char const *)arg2,(char const *)arg3,(char const *)arg4,(char const *)arg5);
  jresult = (jint)result; 
  if (arg2) (*jenv)->ReleaseStringUTFChars(jenv, jarg2, (const char *)arg2);
  if (arg3) (*jenv)->ReleaseStringUTFChars(jenv, jarg3, (const char *)arg3);
  if (arg4) (*jenv)->ReleaseStringUTFChars(jenv, jarg4, (const char *)arg4);
  if (arg5) (*jenv)->ReleaseStringUTFChars(jenv, jarg5, (const char *)arg5);
  return jresult;
}


SWIGEXPORT jint JNICALL Java_com_nordsec_telio_libtelioJNI_Telio_1connectToExitNodePostquantum(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jstring jarg2, jstring jarg3, jstring jarg4, jstring jarg5) {
  jint jresult = 0 ;
  struct telio *arg1 = (struct telio *) 0 ;
  char *arg2 = (char *) 0 ;
  char *arg3 = (char *) 0 ;
  char *arg4 = (char *) 0 ;
  char *arg5 = (char *) 0 ;
  enum telio_result result;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(struct telio **)&jarg1; 
  arg2 = 0;
  if (jarg2) {
    arg2 = (char *)(*jenv)->GetStringUTFChars(jenv, jarg2, 0);
    if (!arg2) return 0;
  }
  arg3 = 0;
  if (jarg3) {
    arg3 = (char *)(*jenv)->GetStringUTFChars(jenv, jarg3, 0);
    if (!arg3) return 0;
  }
  arg4 = 0;
  if (jarg4) {
    arg4 = (char *)(*jenv)->GetStringUTFChars(jenv, jarg4, 0);
    if (!arg4) return 0;
  }
  arg5 = 0;
  if (jarg5) {
    arg5 = (char *)(*jenv)->GetStringUTFChars(jenv, jarg5, 0);
    if (!arg5) return 0;
  }
  result = (enum telio_result)telio_connect_to_exit_node_postquantum(arg1,(char const *)arg2,(char const *)arg3,(char const *)arg4,(char const *)arg5);
  jresult = (jint)result; 
  if (arg2) (*jenv)->ReleaseStringUTFChars(jenv, jarg2, (const char *)arg2);
  if (arg3) (*jenv)->ReleaseStringUTFChars(jenv, jarg3, (const char *)arg3);
  if (arg4) (*jenv)->ReleaseStringUTFChars(jenv, jarg4, (const char *)arg4);
  if (arg5) (*jenv)->ReleaseStringUTFChars(jenv, jarg5, (const char *)arg5);
  return jresult;
}


SWIGEXPORT jint JNICALL Java_com_nordsec_telio_libtelioJNI_Telio_1disconnectFromExitNode(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jstring jarg2) {
  jint jresult = 0 ;
  struct telio *arg1 = (struct telio *) 0 ;
  char *arg2 = (char *) 0 ;
  enum telio_result result;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(struct telio **)&jarg1; 
  arg2 = 0;
  if (jarg2) {
    arg2 = (char *)(*jenv)->GetStringUTFChars(jenv, jarg2, 0);
    if (!arg2) return 0;
  }
  result = (enum telio_result)telio_disconnect_from_exit_node(arg1,(char const *)arg2);
  jresult = (jint)result; 
  if (arg2) (*jenv)->ReleaseStringUTFChars(jenv, jarg2, (const char *)arg2);
  return jresult;
}


SWIGEXPORT jint JNICALL Java_com_nordsec_telio_libtelioJNI_Telio_1disconnectFromExitNodes(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  jint jresult = 0 ;
  struct telio *arg1 = (struct telio *) 0 ;
  enum telio_result result;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(struct telio **)&jarg1; 
  result = (enum telio_result)telio_disconnect_from_exit_nodes(arg1);
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT jint JNICALL Java_com_nordsec_telio_libtelioJNI_Telio_1setMeshnet(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jstring jarg2) {
  jint jresult = 0 ;
  struct telio *arg1 = (struct telio *) 0 ;
  char *arg2 = (char *) 0 ;
  enum telio_result result;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(struct telio **)&jarg1; 
  arg2 = 0;
  if (jarg2) {
    arg2 = (char *)(*jenv)->GetStringUTFChars(jenv, jarg2, 0);
    if (!arg2) return 0;
  }
  result = (enum telio_result)telio_set_meshnet(arg1,(char const *)arg2);
  jresult = (jint)result; 
  if (arg2) (*jenv)->ReleaseStringUTFChars(jenv, jarg2, (const char *)arg2);
  return jresult;
}


SWIGEXPORT jint JNICALL Java_com_nordsec_telio_libtelioJNI_Telio_1setMeshnetOff(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  jint jresult = 0 ;
  struct telio *arg1 = (struct telio *) 0 ;
  enum telio_result result;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(struct telio **)&jarg1; 
  result = (enum telio_result)telio_set_meshnet_off(arg1);
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT jint JNICALL Java_com_nordsec_telio_libtelioJNI_Telio_1generateStackPanic(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  jint jresult = 0 ;
  struct telio *arg1 = (struct telio *) 0 ;
  enum telio_result result;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(struct telio **)&jarg1; 
  result = (enum telio_result)telio_generate_stack_panic(arg1);
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT jstring JNICALL Java_com_nordsec_telio_libtelioJNI_Telio_1generateSecretKey(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  jstring jresult = 0 ;
  struct telio *arg1 = (struct telio *) 0 ;
  char *result = 0 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(struct telio **)&jarg1; 
  result = (char *)telio_generate_secret_key(arg1);
  if (result) jresult = (*jenv)->NewStringUTF(jenv, (const char *)result);
  free(result);
  return jresult;
}


SWIGEXPORT jstring JNICALL Java_com_nordsec_telio_libtelioJNI_Telio_1generatePublicKey(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jstring jarg2) {
  jstring jresult = 0 ;
  struct telio *arg1 = (struct telio *) 0 ;
  char *arg2 = (char *) 0 ;
  char *result = 0 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(struct telio **)&jarg1; 
  arg2 = 0;
  if (jarg2) {
    arg2 = (char *)(*jenv)->GetStringUTFChars(jenv, jarg2, 0);
    if (!arg2) return 0;
  }
  result = (char *)telio_generate_public_key(arg1,(char const *)arg2);
  if (result) jresult = (*jenv)->NewStringUTF(jenv, (const char *)result);
  if (arg2) (*jenv)->ReleaseStringUTFChars(jenv, jarg2, (const char *)arg2);
  free(result);
  return jresult;
}


SWIGEXPORT jstring JNICALL Java_com_nordsec_telio_libtelioJNI_Telio_1getStatusMap(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  jstring jresult = 0 ;
  struct telio *arg1 = (struct telio *) 0 ;
  char *result = 0 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(struct telio **)&jarg1; 
  result = (char *)telio_get_status_map(arg1);
  if (result) jresult = (*jenv)->NewStringUTF(jenv, (const char *)result);
  free(result);
  return jresult;
}


SWIGEXPORT jstring JNICALL Java_com_nordsec_telio_libtelioJNI_Telio_1getLastError(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  jstring jresult = 0 ;
  struct telio *arg1 = (struct telio *) 0 ;
  char *result = 0 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(struct telio **)&jarg1; 
  result = (char *)telio_get_last_error(arg1);
  if (result) jresult = (*jenv)->NewStringUTF(jenv, (const char *)result);
  free(result);
  return jresult;
}


SWIGEXPORT jstring JNICALL Java_com_nordsec_telio_libtelioJNI_Telio_1getVersionTag(JNIEnv *jenv, jclass jcls) {
  jstring jresult = 0 ;
  char *result = 0 ;
  
  (void)jenv;
  (void)jcls;
  result = (char *)telio_get_version_tag();
  if (result) jresult = (*jenv)->NewStringUTF(jenv, (const char *)result);
  free(result);
  return jresult;
}


SWIGEXPORT jstring JNICALL Java_com_nordsec_telio_libtelioJNI_Telio_1getCommitSha(JNIEnv *jenv, jclass jcls) {
  jstring jresult = 0 ;
  char *result = 0 ;
  
  (void)jenv;
  (void)jcls;
  result = (char *)telio_get_commit_sha();
  if (result) jresult = (*jenv)->NewStringUTF(jenv, (const char *)result);
  free(result);
  return jresult;
}


#ifdef __cplusplus
}
#endif

