/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.2
 *
 * This file is not intended to be easily readable and contains a number of
 * coding conventions designed to improve portability and efficiency. Do not make
 * changes to this file unless you know what you are doing--modify the SWIG
 * interface file instead.
 * ----------------------------------------------------------------------------- */

/* source: ffi/bindings/telio.i */

#define SWIGMODULE teliogo
/* -----------------------------------------------------------------------------
 *  This section contains generic SWIG labels for method/variable
 *  declarations/attributes, and other compiler dependent labels.
 * ----------------------------------------------------------------------------- */

/* template workaround for compilers that cannot correctly implement the C++ standard */
#ifndef SWIGTEMPLATEDISAMBIGUATOR
# if defined(__SUNPRO_CC) && (__SUNPRO_CC <= 0x560)
#  define SWIGTEMPLATEDISAMBIGUATOR template
# elif defined(__HP_aCC)
/* Needed even with `aCC -AA' when `aCC -V' reports HP ANSI C++ B3910B A.03.55 */
/* If we find a maximum version that requires this, the test would be __HP_aCC <= 35500 for A.03.55 */
#  define SWIGTEMPLATEDISAMBIGUATOR template
# else
#  define SWIGTEMPLATEDISAMBIGUATOR
# endif
#endif

/* inline attribute */
#ifndef SWIGINLINE
# if defined(__cplusplus) || (defined(__GNUC__) && !defined(__STRICT_ANSI__))
#   define SWIGINLINE inline
# else
#   define SWIGINLINE
# endif
#endif

/* attribute recognised by some compilers to avoid 'unused' warnings */
#ifndef SWIGUNUSED
# if defined(__GNUC__)
#   if !(defined(__cplusplus)) || (__GNUC__ > 3 || (__GNUC__ == 3 && __GNUC_MINOR__ >= 4))
#     define SWIGUNUSED __attribute__ ((__unused__))
#   else
#     define SWIGUNUSED
#   endif
# elif defined(__ICC)
#   define SWIGUNUSED __attribute__ ((__unused__))
# else
#   define SWIGUNUSED
# endif
#endif

#ifndef SWIG_MSC_UNSUPPRESS_4505
# if defined(_MSC_VER)
#   pragma warning(disable : 4505) /* unreferenced local function has been removed */
# endif
#endif

#ifndef SWIGUNUSEDPARM
# ifdef __cplusplus
#   define SWIGUNUSEDPARM(p)
# else
#   define SWIGUNUSEDPARM(p) p SWIGUNUSED
# endif
#endif

/* internal SWIG method */
#ifndef SWIGINTERN
# define SWIGINTERN static SWIGUNUSED
#endif

/* internal inline SWIG method */
#ifndef SWIGINTERNINLINE
# define SWIGINTERNINLINE SWIGINTERN SWIGINLINE
#endif

/* exporting methods */
#if defined(__GNUC__)
#  if (__GNUC__ >= 4) || (__GNUC__ == 3 && __GNUC_MINOR__ >= 4)
#    ifndef GCC_HASCLASSVISIBILITY
#      define GCC_HASCLASSVISIBILITY
#    endif
#  endif
#endif

#ifndef SWIGEXPORT
# if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
#   if defined(STATIC_LINKED)
#     define SWIGEXPORT
#   else
#     define SWIGEXPORT __declspec(dllexport)
#   endif
# else
#   if defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
#     define SWIGEXPORT __attribute__ ((visibility("default")))
#   else
#     define SWIGEXPORT
#   endif
# endif
#endif

/* calling conventions for Windows */
#ifndef SWIGSTDCALL
# if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
#   define SWIGSTDCALL __stdcall
# else
#   define SWIGSTDCALL
# endif
#endif

/* Deal with Microsoft's attempt at deprecating C standard runtime functions */
#if !defined(SWIG_NO_CRT_SECURE_NO_DEPRECATE) && defined(_MSC_VER) && !defined(_CRT_SECURE_NO_DEPRECATE)
# define _CRT_SECURE_NO_DEPRECATE
#endif

/* Deal with Microsoft's attempt at deprecating methods in the standard C++ library */
#if !defined(SWIG_NO_SCL_SECURE_NO_DEPRECATE) && defined(_MSC_VER) && !defined(_SCL_SECURE_NO_DEPRECATE)
# define _SCL_SECURE_NO_DEPRECATE
#endif

/* Deal with Apple's deprecated 'AssertMacros.h' from Carbon-framework */
#if defined(__APPLE__) && !defined(__ASSERT_MACROS_DEFINE_VERSIONS_WITHOUT_UNDERSCORES)
# define __ASSERT_MACROS_DEFINE_VERSIONS_WITHOUT_UNDERSCORES 0
#endif

/* Intel's compiler complains if a variable which was never initialised is
 * cast to void, which is a common idiom which we use to indicate that we
 * are aware a variable isn't used.  So we just silence that warning.
 * See: https://github.com/swig/swig/issues/192 for more discussion.
 */
#ifdef __INTEL_COMPILER
# pragma warning disable 592
#endif


#include <stddef.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <sys/types.h>



typedef int intgo;
typedef unsigned int uintgo;


# if !defined(__clang__) && (defined(__i386__) || defined(__x86_64__))
#   define SWIGSTRUCTPACKED __attribute__((__packed__, __gcc_struct__))
# else
#   define SWIGSTRUCTPACKED __attribute__((__packed__))
# endif



typedef struct { char *p; intgo n; } _gostring_;
typedef struct { void* array; intgo len; intgo cap; } _goslice_;




#define swiggo_size_assert_eq(x, y, name) typedef char name[(x-y)*(x-y)*-2+1];
#define swiggo_size_assert(t, n) swiggo_size_assert_eq(sizeof(t), n, swiggo_sizeof_##t##_is_not_##n)

swiggo_size_assert(char, 1)
swiggo_size_assert(short, 2)
swiggo_size_assert(int, 4)
typedef long long swiggo_long_long;
swiggo_size_assert(swiggo_long_long, 8)
swiggo_size_assert(float, 4)
swiggo_size_assert(double, 8)

#ifdef __cplusplus
extern "C" {
#endif
extern void crosscall2(void (*fn)(void *, int), void *, int);
extern char* _cgo_topofstack(void) __attribute__ ((weak));
extern void _cgo_allocate(void *, int);
extern void _cgo_panic(void *, int);
#ifdef __cplusplus
}
#endif

static char *_swig_topofstack() {
  if (_cgo_topofstack) {
    return _cgo_topofstack();
  } else {
    return 0;
  }
}

static void _swig_gopanic(const char *p) {
  struct {
    const char *p;
  } SWIGSTRUCTPACKED a;
  a.p = p;
  crosscall2(_cgo_panic, &a, (int) sizeof a);
}




#define SWIG_contract_assert(expr, msg) \
  if (!(expr)) { _swig_gopanic(msg); } else


static _gostring_ Swig_AllocateString(const char *p, size_t l) {
  _gostring_ ret;
  ret.p = (char*)malloc(l);
  memcpy(ret.p, p, l);
  ret.n = l;
  return ret;
}


static void Swig_free(void* p) {
  free(p);
}

static void* Swig_malloc(int c) {
  return malloc(c);
}


#include "../../telio.h"

SWIGINTERN struct telio *new_telio(char const *features,telio_event_cb events,enum telio_log_level level,telio_logger_cb logger){
        telio *t;
        if (TELIO_RES_OK != telio_new(&t, features, events, level, logger)) {
            return NULL;
        }
        return t;
    }
SWIGINTERN void delete_telio(struct telio *self){
        telio_destroy(self);
    }
#ifdef __cplusplus
extern "C" {
#endif

void _wrap_Swig_free_teliogo_04c12b194a29af94(void *_swig_go_0) {
  void *arg1 = (void *) 0 ;
  
  arg1 = *(void **)&_swig_go_0; 
  
  Swig_free(arg1);
  
}


void *_wrap_Swig_malloc_teliogo_04c12b194a29af94(intgo _swig_go_0) {
  int arg1 ;
  void *result = 0 ;
  void *_swig_go_result;
  
  arg1 = (int)_swig_go_0; 
  
  result = (void *)Swig_malloc(arg1);
  *(void **)&_swig_go_result = (void *)result; 
  return _swig_go_result;
}


intgo _wrap_TELIOADAPTERBORINGTUN_teliogo_04c12b194a29af94() {
  enum telio_adapter_type result;
  intgo _swig_go_result;
  
  
  result = TELIO_ADAPTER_BORING_TUN;
  
  _swig_go_result = (intgo)result; 
  return _swig_go_result;
}


intgo _wrap_TELIOADAPTERLINUXNATIVETUN_teliogo_04c12b194a29af94() {
  enum telio_adapter_type result;
  intgo _swig_go_result;
  
  
  result = TELIO_ADAPTER_LINUX_NATIVE_TUN;
  
  _swig_go_result = (intgo)result; 
  return _swig_go_result;
}


intgo _wrap_TELIOADAPTERWIREGUARDGOTUN_teliogo_04c12b194a29af94() {
  enum telio_adapter_type result;
  intgo _swig_go_result;
  
  
  result = TELIO_ADAPTER_WIREGUARD_GO_TUN;
  
  _swig_go_result = (intgo)result; 
  return _swig_go_result;
}


intgo _wrap_TELIOADAPTERWINDOWSNATIVETUN_teliogo_04c12b194a29af94() {
  enum telio_adapter_type result;
  intgo _swig_go_result;
  
  
  result = TELIO_ADAPTER_WINDOWS_NATIVE_TUN;
  
  _swig_go_result = (intgo)result; 
  return _swig_go_result;
}


intgo _wrap_TELIOLOGCRITICAL_teliogo_04c12b194a29af94() {
  enum telio_log_level result;
  intgo _swig_go_result;
  
  
  result = TELIO_LOG_CRITICAL;
  
  _swig_go_result = (intgo)result; 
  return _swig_go_result;
}


intgo _wrap_TELIOLOGERROR_teliogo_04c12b194a29af94() {
  enum telio_log_level result;
  intgo _swig_go_result;
  
  
  result = TELIO_LOG_ERROR;
  
  _swig_go_result = (intgo)result; 
  return _swig_go_result;
}


intgo _wrap_TELIOLOGWARNING_teliogo_04c12b194a29af94() {
  enum telio_log_level result;
  intgo _swig_go_result;
  
  
  result = TELIO_LOG_WARNING;
  
  _swig_go_result = (intgo)result; 
  return _swig_go_result;
}


intgo _wrap_TELIOLOGINFO_teliogo_04c12b194a29af94() {
  enum telio_log_level result;
  intgo _swig_go_result;
  
  
  result = TELIO_LOG_INFO;
  
  _swig_go_result = (intgo)result; 
  return _swig_go_result;
}


intgo _wrap_TELIOLOGDEBUG_teliogo_04c12b194a29af94() {
  enum telio_log_level result;
  intgo _swig_go_result;
  
  
  result = TELIO_LOG_DEBUG;
  
  _swig_go_result = (intgo)result; 
  return _swig_go_result;
}


intgo _wrap_TELIOLOGTRACE_teliogo_04c12b194a29af94() {
  enum telio_log_level result;
  intgo _swig_go_result;
  
  
  result = TELIO_LOG_TRACE;
  
  _swig_go_result = (intgo)result; 
  return _swig_go_result;
}


intgo _wrap_TELIORESOK_teliogo_04c12b194a29af94() {
  enum telio_result result;
  intgo _swig_go_result;
  
  
  result = TELIO_RES_OK;
  
  _swig_go_result = (intgo)result; 
  return _swig_go_result;
}


intgo _wrap_TELIORESERROR_teliogo_04c12b194a29af94() {
  enum telio_result result;
  intgo _swig_go_result;
  
  
  result = TELIO_RES_ERROR;
  
  _swig_go_result = (intgo)result; 
  return _swig_go_result;
}


intgo _wrap_TELIORESINVALIDKEY_teliogo_04c12b194a29af94() {
  enum telio_result result;
  intgo _swig_go_result;
  
  
  result = TELIO_RES_INVALID_KEY;
  
  _swig_go_result = (intgo)result; 
  return _swig_go_result;
}


intgo _wrap_TELIORESBADCONFIG_teliogo_04c12b194a29af94() {
  enum telio_result result;
  intgo _swig_go_result;
  
  
  result = TELIO_RES_BAD_CONFIG;
  
  _swig_go_result = (intgo)result; 
  return _swig_go_result;
}


intgo _wrap_TELIORESLOCKERROR_teliogo_04c12b194a29af94() {
  enum telio_result result;
  intgo _swig_go_result;
  
  
  result = TELIO_RES_LOCK_ERROR;
  
  _swig_go_result = (intgo)result; 
  return _swig_go_result;
}


intgo _wrap_TELIORESINVALIDSTRING_teliogo_04c12b194a29af94() {
  enum telio_result result;
  intgo _swig_go_result;
  
  
  result = TELIO_RES_INVALID_STRING;
  
  _swig_go_result = (intgo)result; 
  return _swig_go_result;
}


intgo _wrap_TELIORESALREADYSTARTED_teliogo_04c12b194a29af94() {
  enum telio_result result;
  intgo _swig_go_result;
  
  
  result = TELIO_RES_ALREADY_STARTED;
  
  _swig_go_result = (intgo)result; 
  return _swig_go_result;
}


void _wrap_TelioEventCb_Ctx_set_teliogo_04c12b194a29af94(struct telio_event_cb *_swig_go_0, void *_swig_go_1) {
  struct telio_event_cb *arg1 = (struct telio_event_cb *) 0 ;
  void *arg2 = (void *) 0 ;
  
  arg1 = *(struct telio_event_cb **)&_swig_go_0; 
  arg2 = *(void **)&_swig_go_1; 
  
  if (arg1) (arg1)->ctx = arg2;
  
}


void *_wrap_TelioEventCb_Ctx_get_teliogo_04c12b194a29af94(struct telio_event_cb *_swig_go_0) {
  struct telio_event_cb *arg1 = (struct telio_event_cb *) 0 ;
  void *result = 0 ;
  void *_swig_go_result;
  
  arg1 = *(struct telio_event_cb **)&_swig_go_0; 
  
  result = (void *) ((arg1)->ctx);
  *(void **)&_swig_go_result = (void *)result; 
  return _swig_go_result;
}


void _wrap_TelioEventCb_Cb_set_teliogo_04c12b194a29af94(struct telio_event_cb *_swig_go_0, void* _swig_go_1) {
  struct telio_event_cb *arg1 = (struct telio_event_cb *) 0 ;
  telio_event_fn arg2 = (telio_event_fn) 0 ;
  
  arg1 = *(struct telio_event_cb **)&_swig_go_0; 
  arg2 = *(telio_event_fn *)&_swig_go_1; 
  
  if (arg1) (arg1)->cb = arg2;
  
}


void* _wrap_TelioEventCb_Cb_get_teliogo_04c12b194a29af94(struct telio_event_cb *_swig_go_0) {
  struct telio_event_cb *arg1 = (struct telio_event_cb *) 0 ;
  telio_event_fn result;
  void* _swig_go_result;
  
  arg1 = *(struct telio_event_cb **)&_swig_go_0; 
  
  result = (telio_event_fn) ((arg1)->cb);
  *(telio_event_fn *)&_swig_go_result = (telio_event_fn)result; 
  return _swig_go_result;
}


struct telio_event_cb *_wrap_new_TelioEventCb_teliogo_04c12b194a29af94() {
  struct telio_event_cb *result = 0 ;
  struct telio_event_cb *_swig_go_result;
  
  
  result = (struct telio_event_cb *)calloc(1, sizeof(struct telio_event_cb));
  *(struct telio_event_cb **)&_swig_go_result = (struct telio_event_cb *)result; 
  return _swig_go_result;
}


void _wrap_delete_TelioEventCb_teliogo_04c12b194a29af94(struct telio_event_cb *_swig_go_0) {
  struct telio_event_cb *arg1 = (struct telio_event_cb *) 0 ;
  
  arg1 = *(struct telio_event_cb **)&_swig_go_0; 
  
  free((char *) arg1);
  
}


void _wrap_TelioLoggerCb_Ctx_set_teliogo_04c12b194a29af94(struct telio_logger_cb *_swig_go_0, void *_swig_go_1) {
  struct telio_logger_cb *arg1 = (struct telio_logger_cb *) 0 ;
  void *arg2 = (void *) 0 ;
  
  arg1 = *(struct telio_logger_cb **)&_swig_go_0; 
  arg2 = *(void **)&_swig_go_1; 
  
  if (arg1) (arg1)->ctx = arg2;
  
}


void *_wrap_TelioLoggerCb_Ctx_get_teliogo_04c12b194a29af94(struct telio_logger_cb *_swig_go_0) {
  struct telio_logger_cb *arg1 = (struct telio_logger_cb *) 0 ;
  void *result = 0 ;
  void *_swig_go_result;
  
  arg1 = *(struct telio_logger_cb **)&_swig_go_0; 
  
  result = (void *) ((arg1)->ctx);
  *(void **)&_swig_go_result = (void *)result; 
  return _swig_go_result;
}


void _wrap_TelioLoggerCb_Cb_set_teliogo_04c12b194a29af94(struct telio_logger_cb *_swig_go_0, void* _swig_go_1) {
  struct telio_logger_cb *arg1 = (struct telio_logger_cb *) 0 ;
  telio_logger_fn arg2 = (telio_logger_fn) 0 ;
  
  arg1 = *(struct telio_logger_cb **)&_swig_go_0; 
  arg2 = *(telio_logger_fn *)&_swig_go_1; 
  
  if (arg1) (arg1)->cb = arg2;
  
}


void* _wrap_TelioLoggerCb_Cb_get_teliogo_04c12b194a29af94(struct telio_logger_cb *_swig_go_0) {
  struct telio_logger_cb *arg1 = (struct telio_logger_cb *) 0 ;
  telio_logger_fn result;
  void* _swig_go_result;
  
  arg1 = *(struct telio_logger_cb **)&_swig_go_0; 
  
  result = (telio_logger_fn) ((arg1)->cb);
  *(telio_logger_fn *)&_swig_go_result = (telio_logger_fn)result; 
  return _swig_go_result;
}


struct telio_logger_cb *_wrap_new_TelioLoggerCb_teliogo_04c12b194a29af94() {
  struct telio_logger_cb *result = 0 ;
  struct telio_logger_cb *_swig_go_result;
  
  
  result = (struct telio_logger_cb *)calloc(1, sizeof(struct telio_logger_cb));
  *(struct telio_logger_cb **)&_swig_go_result = (struct telio_logger_cb *)result; 
  return _swig_go_result;
}


void _wrap_delete_TelioLoggerCb_teliogo_04c12b194a29af94(struct telio_logger_cb *_swig_go_0) {
  struct telio_logger_cb *arg1 = (struct telio_logger_cb *) 0 ;
  
  arg1 = *(struct telio_logger_cb **)&_swig_go_0; 
  
  free((char *) arg1);
  
}


intgo _wrap_Telio_GetDefaultAdapter_teliogo_04c12b194a29af94() {
  enum telio_adapter_type result;
  intgo _swig_go_result;
  
  
  result = (enum telio_adapter_type)telio_get_default_adapter();
  _swig_go_result = (intgo)result; 
  return _swig_go_result;
}


struct telio *_wrap_new_Telio_teliogo_04c12b194a29af94(_gostring_ _swig_go_0, telio_event_cb _swig_go_1, intgo _swig_go_2, telio_logger_cb _swig_go_3) {
  char *arg1 = (char *) 0 ;
  telio_event_cb arg2 ;
  enum telio_log_level arg3 ;
  telio_logger_cb arg4 ;
  struct telio *result = 0 ;
  struct telio *_swig_go_result;
  
  
  arg1 = (char *)malloc(_swig_go_0.n + 1);
  memcpy(arg1, _swig_go_0.p, _swig_go_0.n);
  arg1[_swig_go_0.n] = '\0';
  
  {
    arg2 = _swig_go_1;
  }
  arg3 = (enum telio_log_level)_swig_go_2; 
  {
    arg4 = _swig_go_3;
  }
  
  result = (struct telio *)new_telio((char const *)arg1,arg2,arg3,arg4);
  *(struct telio **)&_swig_go_result = (struct telio *)result; 
  free(arg1); 
  return _swig_go_result;
}


void _wrap_delete_Telio_teliogo_04c12b194a29af94(struct telio *_swig_go_0) {
  struct telio *arg1 = (struct telio *) 0 ;
  
  arg1 = *(struct telio **)&_swig_go_0; 
  
  delete_telio(arg1);
  
}


intgo _wrap_Telio_Start_teliogo_04c12b194a29af94(struct telio *_swig_go_0, _gostring_ _swig_go_1, intgo _swig_go_2) {
  struct telio *arg1 = (struct telio *) 0 ;
  char *arg2 = (char *) 0 ;
  enum telio_adapter_type arg3 ;
  enum telio_result result;
  intgo _swig_go_result;
  
  arg1 = *(struct telio **)&_swig_go_0; 
  
  arg2 = (char *)malloc(_swig_go_1.n + 1);
  memcpy(arg2, _swig_go_1.p, _swig_go_1.n);
  arg2[_swig_go_1.n] = '\0';
  
  arg3 = (enum telio_adapter_type)_swig_go_2; 
  
  result = (enum telio_result)telio_start(arg1,(char const *)arg2,arg3);
  _swig_go_result = (intgo)result; 
  free(arg2); 
  return _swig_go_result;
}


intgo _wrap_Telio_StartNamed_teliogo_04c12b194a29af94(struct telio *_swig_go_0, _gostring_ _swig_go_1, intgo _swig_go_2, _gostring_ _swig_go_3) {
  struct telio *arg1 = (struct telio *) 0 ;
  char *arg2 = (char *) 0 ;
  enum telio_adapter_type arg3 ;
  char *arg4 = (char *) 0 ;
  enum telio_result result;
  intgo _swig_go_result;
  
  arg1 = *(struct telio **)&_swig_go_0; 
  
  arg2 = (char *)malloc(_swig_go_1.n + 1);
  memcpy(arg2, _swig_go_1.p, _swig_go_1.n);
  arg2[_swig_go_1.n] = '\0';
  
  arg3 = (enum telio_adapter_type)_swig_go_2; 
  
  arg4 = (char *)malloc(_swig_go_3.n + 1);
  memcpy(arg4, _swig_go_3.p, _swig_go_3.n);
  arg4[_swig_go_3.n] = '\0';
  
  
  result = (enum telio_result)telio_start_named(arg1,(char const *)arg2,arg3,(char const *)arg4);
  _swig_go_result = (intgo)result; 
  free(arg2); 
  free(arg4); 
  return _swig_go_result;
}


intgo _wrap_Telio_StartWithTun_teliogo_04c12b194a29af94(struct telio *_swig_go_0, _gostring_ _swig_go_1, intgo _swig_go_2, intgo _swig_go_3) {
  struct telio *arg1 = (struct telio *) 0 ;
  char *arg2 = (char *) 0 ;
  enum telio_adapter_type arg3 ;
  int arg4 ;
  enum telio_result result;
  intgo _swig_go_result;
  
  arg1 = *(struct telio **)&_swig_go_0; 
  
  arg2 = (char *)malloc(_swig_go_1.n + 1);
  memcpy(arg2, _swig_go_1.p, _swig_go_1.n);
  arg2[_swig_go_1.n] = '\0';
  
  arg3 = (enum telio_adapter_type)_swig_go_2; 
  arg4 = (int)_swig_go_3; 
  
  result = (enum telio_result)telio_start_with_tun(arg1,(char const *)arg2,arg3,arg4);
  _swig_go_result = (intgo)result; 
  free(arg2); 
  return _swig_go_result;
}


intgo _wrap_Telio_EnableMagicDns_teliogo_04c12b194a29af94(struct telio *_swig_go_0, _gostring_ _swig_go_1) {
  struct telio *arg1 = (struct telio *) 0 ;
  char *arg2 = (char *) 0 ;
  enum telio_result result;
  intgo _swig_go_result;
  
  arg1 = *(struct telio **)&_swig_go_0; 
  
  arg2 = (char *)malloc(_swig_go_1.n + 1);
  memcpy(arg2, _swig_go_1.p, _swig_go_1.n);
  arg2[_swig_go_1.n] = '\0';
  
  
  result = (enum telio_result)telio_enable_magic_dns(arg1,(char const *)arg2);
  _swig_go_result = (intgo)result; 
  free(arg2); 
  return _swig_go_result;
}


intgo _wrap_Telio_DisableMagicDns_teliogo_04c12b194a29af94(struct telio *_swig_go_0) {
  struct telio *arg1 = (struct telio *) 0 ;
  enum telio_result result;
  intgo _swig_go_result;
  
  arg1 = *(struct telio **)&_swig_go_0; 
  
  result = (enum telio_result)telio_disable_magic_dns(arg1);
  _swig_go_result = (intgo)result; 
  return _swig_go_result;
}


intgo _wrap_Telio_Stop_teliogo_04c12b194a29af94(struct telio *_swig_go_0) {
  struct telio *arg1 = (struct telio *) 0 ;
  enum telio_result result;
  intgo _swig_go_result;
  
  arg1 = *(struct telio **)&_swig_go_0; 
  
  result = (enum telio_result)telio_stop(arg1);
  _swig_go_result = (intgo)result; 
  return _swig_go_result;
}


long long _wrap_Telio_GetAdapterLuid_teliogo_04c12b194a29af94(struct telio *_swig_go_0) {
  struct telio *arg1 = (struct telio *) 0 ;
  unsigned long long result;
  long long _swig_go_result;
  
  arg1 = *(struct telio **)&_swig_go_0; 
  
  result = (unsigned long long)telio_get_adapter_luid(arg1);
  _swig_go_result = result; 
  return _swig_go_result;
}


intgo _wrap_Telio_SetPrivateKey_teliogo_04c12b194a29af94(struct telio *_swig_go_0, _gostring_ _swig_go_1) {
  struct telio *arg1 = (struct telio *) 0 ;
  char *arg2 = (char *) 0 ;
  enum telio_result result;
  intgo _swig_go_result;
  
  arg1 = *(struct telio **)&_swig_go_0; 
  
  arg2 = (char *)malloc(_swig_go_1.n + 1);
  memcpy(arg2, _swig_go_1.p, _swig_go_1.n);
  arg2[_swig_go_1.n] = '\0';
  
  
  result = (enum telio_result)telio_set_private_key(arg1,(char const *)arg2);
  _swig_go_result = (intgo)result; 
  free(arg2); 
  return _swig_go_result;
}


_gostring_ _wrap_Telio_GetPrivateKey_teliogo_04c12b194a29af94(struct telio *_swig_go_0) {
  struct telio *arg1 = (struct telio *) 0 ;
  char *result = 0 ;
  _gostring_ _swig_go_result;
  
  arg1 = *(struct telio **)&_swig_go_0; 
  
  result = (char *)telio_get_private_key(arg1);
  _swig_go_result = Swig_AllocateString((char*)result, result ? strlen((char*)result) : 0); 
  return _swig_go_result;
}


intgo _wrap_Telio_SetFwmark_teliogo_04c12b194a29af94(struct telio *_swig_go_0, intgo _swig_go_1) {
  struct telio *arg1 = (struct telio *) 0 ;
  unsigned int arg2 ;
  enum telio_result result;
  intgo _swig_go_result;
  
  arg1 = *(struct telio **)&_swig_go_0; 
  arg2 = (unsigned int)_swig_go_1; 
  
  result = (enum telio_result)telio_set_fwmark(arg1,arg2);
  _swig_go_result = (intgo)result; 
  return _swig_go_result;
}


intgo _wrap_Telio_NotifyNetworkChange_teliogo_04c12b194a29af94(struct telio *_swig_go_0, _gostring_ _swig_go_1) {
  struct telio *arg1 = (struct telio *) 0 ;
  char *arg2 = (char *) 0 ;
  enum telio_result result;
  intgo _swig_go_result;
  
  arg1 = *(struct telio **)&_swig_go_0; 
  
  arg2 = (char *)malloc(_swig_go_1.n + 1);
  memcpy(arg2, _swig_go_1.p, _swig_go_1.n);
  arg2[_swig_go_1.n] = '\0';
  
  
  result = (enum telio_result)telio_notify_network_change(arg1,(char const *)arg2);
  _swig_go_result = (intgo)result; 
  free(arg2); 
  return _swig_go_result;
}


intgo _wrap_Telio_ConnectToExitNode_teliogo_04c12b194a29af94(struct telio *_swig_go_0, _gostring_ _swig_go_1, _gostring_ _swig_go_2, _gostring_ _swig_go_3) {
  struct telio *arg1 = (struct telio *) 0 ;
  char *arg2 = (char *) 0 ;
  char *arg3 = (char *) 0 ;
  char *arg4 = (char *) 0 ;
  enum telio_result result;
  intgo _swig_go_result;
  
  arg1 = *(struct telio **)&_swig_go_0; 
  
  arg2 = (char *)malloc(_swig_go_1.n + 1);
  memcpy(arg2, _swig_go_1.p, _swig_go_1.n);
  arg2[_swig_go_1.n] = '\0';
  
  
  arg3 = (char *)malloc(_swig_go_2.n + 1);
  memcpy(arg3, _swig_go_2.p, _swig_go_2.n);
  arg3[_swig_go_2.n] = '\0';
  
  
  arg4 = (char *)malloc(_swig_go_3.n + 1);
  memcpy(arg4, _swig_go_3.p, _swig_go_3.n);
  arg4[_swig_go_3.n] = '\0';
  
  
  result = (enum telio_result)telio_connect_to_exit_node(arg1,(char const *)arg2,(char const *)arg3,(char const *)arg4);
  _swig_go_result = (intgo)result; 
  free(arg2); 
  free(arg3); 
  free(arg4); 
  return _swig_go_result;
}


intgo _wrap_Telio_ConnectToExitNodeWithId_teliogo_04c12b194a29af94(struct telio *_swig_go_0, _gostring_ _swig_go_1, _gostring_ _swig_go_2, _gostring_ _swig_go_3, _gostring_ _swig_go_4) {
  struct telio *arg1 = (struct telio *) 0 ;
  char *arg2 = (char *) 0 ;
  char *arg3 = (char *) 0 ;
  char *arg4 = (char *) 0 ;
  char *arg5 = (char *) 0 ;
  enum telio_result result;
  intgo _swig_go_result;
  
  arg1 = *(struct telio **)&_swig_go_0; 
  
  arg2 = (char *)malloc(_swig_go_1.n + 1);
  memcpy(arg2, _swig_go_1.p, _swig_go_1.n);
  arg2[_swig_go_1.n] = '\0';
  
  
  arg3 = (char *)malloc(_swig_go_2.n + 1);
  memcpy(arg3, _swig_go_2.p, _swig_go_2.n);
  arg3[_swig_go_2.n] = '\0';
  
  
  arg4 = (char *)malloc(_swig_go_3.n + 1);
  memcpy(arg4, _swig_go_3.p, _swig_go_3.n);
  arg4[_swig_go_3.n] = '\0';
  
  
  arg5 = (char *)malloc(_swig_go_4.n + 1);
  memcpy(arg5, _swig_go_4.p, _swig_go_4.n);
  arg5[_swig_go_4.n] = '\0';
  
  
  result = (enum telio_result)telio_connect_to_exit_node_with_id(arg1,(char const *)arg2,(char const *)arg3,(char const *)arg4,(char const *)arg5);
  _swig_go_result = (intgo)result; 
  free(arg2); 
  free(arg3); 
  free(arg4); 
  free(arg5); 
  return _swig_go_result;
}


intgo _wrap_Telio_DisconnectFromExitNode_teliogo_04c12b194a29af94(struct telio *_swig_go_0, _gostring_ _swig_go_1) {
  struct telio *arg1 = (struct telio *) 0 ;
  char *arg2 = (char *) 0 ;
  enum telio_result result;
  intgo _swig_go_result;
  
  arg1 = *(struct telio **)&_swig_go_0; 
  
  arg2 = (char *)malloc(_swig_go_1.n + 1);
  memcpy(arg2, _swig_go_1.p, _swig_go_1.n);
  arg2[_swig_go_1.n] = '\0';
  
  
  result = (enum telio_result)telio_disconnect_from_exit_node(arg1,(char const *)arg2);
  _swig_go_result = (intgo)result; 
  free(arg2); 
  return _swig_go_result;
}


intgo _wrap_Telio_DisconnectFromExitNodes_teliogo_04c12b194a29af94(struct telio *_swig_go_0) {
  struct telio *arg1 = (struct telio *) 0 ;
  enum telio_result result;
  intgo _swig_go_result;
  
  arg1 = *(struct telio **)&_swig_go_0; 
  
  result = (enum telio_result)telio_disconnect_from_exit_nodes(arg1);
  _swig_go_result = (intgo)result; 
  return _swig_go_result;
}


intgo _wrap_Telio_SetMeshnet_teliogo_04c12b194a29af94(struct telio *_swig_go_0, _gostring_ _swig_go_1) {
  struct telio *arg1 = (struct telio *) 0 ;
  char *arg2 = (char *) 0 ;
  enum telio_result result;
  intgo _swig_go_result;
  
  arg1 = *(struct telio **)&_swig_go_0; 
  
  arg2 = (char *)malloc(_swig_go_1.n + 1);
  memcpy(arg2, _swig_go_1.p, _swig_go_1.n);
  arg2[_swig_go_1.n] = '\0';
  
  
  result = (enum telio_result)telio_set_meshnet(arg1,(char const *)arg2);
  _swig_go_result = (intgo)result; 
  free(arg2); 
  return _swig_go_result;
}


intgo _wrap_Telio_SetMeshnetOff_teliogo_04c12b194a29af94(struct telio *_swig_go_0) {
  struct telio *arg1 = (struct telio *) 0 ;
  enum telio_result result;
  intgo _swig_go_result;
  
  arg1 = *(struct telio **)&_swig_go_0; 
  
  result = (enum telio_result)telio_set_meshnet_off(arg1);
  _swig_go_result = (intgo)result; 
  return _swig_go_result;
}


intgo _wrap_Telio_GenerateStackPanic_teliogo_04c12b194a29af94(struct telio *_swig_go_0) {
  struct telio *arg1 = (struct telio *) 0 ;
  enum telio_result result;
  intgo _swig_go_result;
  
  arg1 = *(struct telio **)&_swig_go_0; 
  
  result = (enum telio_result)telio_generate_stack_panic(arg1);
  _swig_go_result = (intgo)result; 
  return _swig_go_result;
}


_gostring_ _wrap_Telio_GenerateSecretKey_teliogo_04c12b194a29af94(struct telio *_swig_go_0) {
  struct telio *arg1 = (struct telio *) 0 ;
  char *result = 0 ;
  _gostring_ _swig_go_result;
  
  arg1 = *(struct telio **)&_swig_go_0; 
  
  result = (char *)telio_generate_secret_key(arg1);
  _swig_go_result = Swig_AllocateString((char*)result, result ? strlen((char*)result) : 0); 
  free(result);
  return _swig_go_result;
}


_gostring_ _wrap_Telio_GeneratePublicKey_teliogo_04c12b194a29af94(struct telio *_swig_go_0, _gostring_ _swig_go_1) {
  struct telio *arg1 = (struct telio *) 0 ;
  char *arg2 = (char *) 0 ;
  char *result = 0 ;
  _gostring_ _swig_go_result;
  
  arg1 = *(struct telio **)&_swig_go_0; 
  
  arg2 = (char *)malloc(_swig_go_1.n + 1);
  memcpy(arg2, _swig_go_1.p, _swig_go_1.n);
  arg2[_swig_go_1.n] = '\0';
  
  
  result = (char *)telio_generate_public_key(arg1,(char const *)arg2);
  _swig_go_result = Swig_AllocateString((char*)result, result ? strlen((char*)result) : 0); 
  free(arg2); 
  free(result);
  return _swig_go_result;
}


_gostring_ _wrap_Telio_GetStatusMap_teliogo_04c12b194a29af94(struct telio *_swig_go_0) {
  struct telio *arg1 = (struct telio *) 0 ;
  char *result = 0 ;
  _gostring_ _swig_go_result;
  
  arg1 = *(struct telio **)&_swig_go_0; 
  
  result = (char *)telio_get_status_map(arg1);
  _swig_go_result = Swig_AllocateString((char*)result, result ? strlen((char*)result) : 0); 
  free(result);
  return _swig_go_result;
}


_gostring_ _wrap_Telio_GetLastError_teliogo_04c12b194a29af94(struct telio *_swig_go_0) {
  struct telio *arg1 = (struct telio *) 0 ;
  char *result = 0 ;
  _gostring_ _swig_go_result;
  
  arg1 = *(struct telio **)&_swig_go_0; 
  
  result = (char *)telio_get_last_error(arg1);
  _swig_go_result = Swig_AllocateString((char*)result, result ? strlen((char*)result) : 0); 
  free(result);
  return _swig_go_result;
}


_gostring_ _wrap_Telio_GetVersionTag_teliogo_04c12b194a29af94() {
  char *result = 0 ;
  _gostring_ _swig_go_result;
  
  
  result = (char *)telio_get_version_tag();
  _swig_go_result = Swig_AllocateString((char*)result, result ? strlen((char*)result) : 0); 
  free(result);
  return _swig_go_result;
}


_gostring_ _wrap_Telio_GetCommitSha_teliogo_04c12b194a29af94() {
  char *result = 0 ;
  _gostring_ _swig_go_result;
  
  
  result = (char *)telio_get_commit_sha();
  _swig_go_result = Swig_AllocateString((char*)result, result ? strlen((char*)result) : 0); 
  free(result);
  return _swig_go_result;
}


#ifdef __cplusplus
}
#endif

