[package]
name = "teliod"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow.workspace = true
clap.workspace = true
serde = { workspace = true, default-features = false }
serde_json.workspace = true
tracing.workspace = true
tracing-appender.workspace = true
tracing-subscriber.workspace = true

nix = "0.28.0"

daemon-common = { version = "0.1.0", path = "../daemon-common" }
telio = { path = "../.." }
