# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: telio-proto/protos/pinger.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database

# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()

DESCRIPTOR = _descriptor.FileDescriptor(
    name="telio-proto/protos/pinger.proto",
    package="",
    syntax="proto3",
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
    serialized_pb=b'\n\x1ftelio-proto/protos/pinger.proto"r\n\x06Pinger\x12"\n\x0cmessage_type\x18\x01 \x01(\x0e\x32\x0c.Pinger.Type\x12\x0f\n\x07session\x18\x02 \x01(\x04\x12\x17\n\x0fstart_timestamp\x18\x03 \x01(\x04"\x1a\n\x04Type\x12\x08\n\x04PING\x10\x00\x12\x08\n\x04PONG\x10\x01\x62\x06proto3',
)

_PINGER_TYPE = _descriptor.EnumDescriptor(
    name="Type",
    full_name="Pinger.Type",
    filename=None,
    file=DESCRIPTOR,
    create_key=_descriptor._internal_create_key,
    values=[
        _descriptor.EnumValueDescriptor(
            name="PING",
            index=0,
            number=0,
            serialized_options=None,
            type=None,
            create_key=_descriptor._internal_create_key,
        ),
        _descriptor.EnumValueDescriptor(
            name="PONG",
            index=1,
            number=1,
            serialized_options=None,
            type=None,
            create_key=_descriptor._internal_create_key,
        ),
    ],
    containing_type=None,
    serialized_options=None,
    serialized_start=123,
    serialized_end=149,
)
_sym_db.RegisterEnumDescriptor(_PINGER_TYPE)


_PINGER = _descriptor.Descriptor(
    name="Pinger",
    full_name="Pinger",
    filename=None,
    file=DESCRIPTOR,
    containing_type=None,
    create_key=_descriptor._internal_create_key,
    fields=[
        _descriptor.FieldDescriptor(
            name="message_type",
            full_name="Pinger.message_type",
            index=0,
            number=1,
            type=14,
            cpp_type=8,
            label=1,
            has_default_value=False,
            default_value=0,
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            serialized_options=None,
            file=DESCRIPTOR,
            create_key=_descriptor._internal_create_key,
        ),
        _descriptor.FieldDescriptor(
            name="session",
            full_name="Pinger.session",
            index=1,
            number=2,
            type=4,
            cpp_type=4,
            label=1,
            has_default_value=False,
            default_value=0,
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            serialized_options=None,
            file=DESCRIPTOR,
            create_key=_descriptor._internal_create_key,
        ),
        _descriptor.FieldDescriptor(
            name="start_timestamp",
            full_name="Pinger.start_timestamp",
            index=2,
            number=3,
            type=4,
            cpp_type=4,
            label=1,
            has_default_value=False,
            default_value=0,
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            serialized_options=None,
            file=DESCRIPTOR,
            create_key=_descriptor._internal_create_key,
        ),
    ],
    extensions=[],
    nested_types=[],
    enum_types=[
        _PINGER_TYPE,
    ],
    serialized_options=None,
    is_extendable=False,
    syntax="proto3",
    extension_ranges=[],
    oneofs=[],
    serialized_start=35,
    serialized_end=149,
)

_PINGER.fields_by_name["message_type"].enum_type = _PINGER_TYPE
_PINGER_TYPE.containing_type = _PINGER
DESCRIPTOR.message_types_by_name["Pinger"] = _PINGER
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Pinger = _reflection.GeneratedProtocolMessageType(
    "Pinger",
    (_message.Message,),
    {
        "DESCRIPTOR": _PINGER,
        "__module__": "telio_proto.protos.pinger_pb2",
        # @@protoc_insertion_point(class_scope:Pinger)
    },
)
_sym_db.RegisterMessage(Pinger)


# @@protoc_insertion_point(module_scope)
