[package]
name = "telio-nat-detect"
version = "0.1.0"
edition = "2018"
license = "GPL-3.0-only"
repository = "https://github.com/NordSecurity/libtelio"
publish = false

[dependencies]
nat-detect.workspace = true
tokio = { workspace = true, features = ["full"] }
