[package]
name = "telio-task"
version = "0.1.0"
edition = "2018"
license = "GPL-3.0-only"
repository = "https://github.com/NordSecurity/libtelio"
publish = false

[features]
default = []
# Compile task crate for testing
test-util = []

[dependencies]
async-trait.workspace = true
futures.workspace = true
tracing.workspace = true
thiserror.workspace = true
tokio = { workspace = true, features = ["full"] }

telio-utils.workspace = true
