[package]
name = "telio-proto-fuzz"
version = "0.0.0"
publish = false
edition = "2018"
license = "GPL-3.0-only"
repository = "https://github.com/NordSecurity/libtelio"

[package.metadata]
cargo-fuzz = true

[dependencies]
libfuzzer-sys = "0.4"
rustls = { version = "0.23", default-features = false, features = ["ring", "std"] }

[dependencies.telio-proto]
path = ".."

# Prevent this from interfering with workspaces
[workspace]
members = ["."]

[profile.release]
debug = 1

[[bin]]
name = "packet"
path = "fuzz_targets/packet.rs"
test = false
doc = false
