#!/usr/bin/env python3

import os

LIBTELIO_ENV_MOOSE_RELEASE_TAG = "v17.0.0-libtelioApp"
LIBTELIO_ENV_NAT_LAB_DEPS_TAG = "v0.3.0"
LIBTELIO_ENV_ANDROID_BUILDER_TAG = "v7.2.2"
LIBTELIO_ENV_LINUX_BUILDER_TAG = "v7.2.3"
LIBTELIO_ENV_WINDOWS_BUILDER_TAG = "v7.2.2"
LIBTELIO_ENV_UNIFFI_GENERATORS_TAG = "v0.28.3-4"
LIBTELIO_ENV_NAT_LAB_WINDOWS_VM_TAG = "v0.0.8"
LIBTELIO_ENV_NAT_LAB_MACOS_VM_TAG = "v0.0.9"
LIBTELIO_ENV_NAT_LAB_LINUX_VM_TAG = "v0.2.2"
LIBTELIO_ENV_OPENWRT_BUILDER_TAG = "24.10.4"


def set_sh():
    print(f"export LIBTELIO_ENV_MOOSE_RELEASE_TAG={LIBTELIO_ENV_MOOSE_RELEASE_TAG}")
    print(f"export LIBTELIO_ENV_NAT_LAB_DEPS_TAG={LIBTELIO_ENV_NAT_LAB_DEPS_TAG}")
    print(f"export LIBTELIO_ENV_ANDROID_BUILDER_TAG={LIBTELIO_ENV_ANDROID_BUILDER_TAG}")
    print(f"export LIBTELIO_ENV_LINUX_BUILDER_TAG={LIBTELIO_ENV_LINUX_BUILDER_TAG}")
    print(f"export LIBTELIO_ENV_WINDOWS_BUILDER_TAG={LIBTELIO_ENV_WINDOWS_BUILDER_TAG}")
    print(
        f"export LIBTELIO_ENV_NAT_LAB_WINDOWS_VM_TAG={LIBTELIO_ENV_NAT_LAB_WINDOWS_VM_TAG}"
    )
    print(
        f"export LIBTELIO_ENV_NAT_LAB_MACOS_VM_TAG={LIBTELIO_ENV_NAT_LAB_MACOS_VM_TAG}"
    )
    print(
        f"export LIBTELIO_ENV_NAT_LAB_LINUX_VM_TAG={LIBTELIO_ENV_NAT_LAB_LINUX_VM_TAG}"
    )


def set_ps1():
    print(f'$env:LIBTELIO_ENV_MOOSE_RELEASE_TAG="{LIBTELIO_ENV_MOOSE_RELEASE_TAG}"')
    print(f'$env:LIBTELIO_ENV_NAT_LAB_DEPS_TAG="{LIBTELIO_ENV_NAT_LAB_DEPS_TAG}"')
    print(f'$env:LIBTELIO_ENV_ANDROID_BUILDER_TAG="{LIBTELIO_ENV_ANDROID_BUILDER_TAG}"')
    print(f'$env:LIBTELIO_ENV_LINUX_BUILDER_TAG="{LIBTELIO_ENV_LINUX_BUILDER_TAG}"')
    print(f'$env:LIBTELIO_ENV_WINDOWS_BUILDER_TAG="{LIBTELIO_ENV_WINDOWS_BUILDER_TAG}"')
    print(
        f'$env:LIBTELIO_ENV_NAT_LAB_WINDOWS_VM_TAG="{LIBTELIO_ENV_NAT_LAB_WINDOWS_VM_TAG}"'
    )
    print(
        f'$env:LIBTELIO_ENV_NAT_LAB_MACOS_VM_TAG="{LIBTELIO_ENV_NAT_LAB_MACOS_VM_TAG}"'
    )
    print(
        f'$env:LIBTELIO_ENV_NAT_LAB_LINUX_VM_TAG="{LIBTELIO_ENV_NAT_LAB_LINUX_VM_TAG}"'
    )


if __name__ == "__main__":
    if os.name == "nt":
        set_ps1()
    else:
        set_sh()
