/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.nordsec.telio;

public final class TelioResult {
  public final static TelioResult RES_OK = new TelioResult("RES_OK", libtelioJNI.RES_OK_get());
  public final static TelioResult RES_ERROR = new TelioResult("RES_ERROR", libtelioJNI.RES_ERROR_get());
  public final static TelioResult RES_INVALID_KEY = new TelioResult("RES_INVALID_KEY", libtelioJNI.RES_INVALID_KEY_get());
  public final static TelioResult RES_BAD_CONFIG = new TelioResult("RES_BAD_CONFIG", libtelioJNI.RES_BAD_CONFIG_get());
  public final static TelioResult RES_LOCK_ERROR = new TelioResult("RES_LOCK_ERROR", libtelioJNI.RES_LOCK_ERROR_get());
  public final static TelioResult RES_INVALID_STRING = new TelioResult("RES_INVALID_STRING", libtelioJNI.RES_INVALID_STRING_get());
  public final static TelioResult RES_ALREADY_STARTED = new TelioResult("RES_ALREADY_STARTED", libtelioJNI.RES_ALREADY_STARTED_get());

  public final int swigValue() {
    return swigValue;
  }

  public String toString() {
    return swigName;
  }

  public static TelioResult swigToEnum(int swigValue) {
    if (swigValue < swigValues.length && swigValue >= 0 && swigValues[swigValue].swigValue == swigValue)
      return swigValues[swigValue];
    for (int i = 0; i < swigValues.length; i++)
      if (swigValues[i].swigValue == swigValue)
        return swigValues[i];
    throw new IllegalArgumentException("No enum " + TelioResult.class + " with value " + swigValue);
  }

  private TelioResult(String swigName) {
    this.swigName = swigName;
    this.swigValue = swigNext++;
  }

  private TelioResult(String swigName, int swigValue) {
    this.swigName = swigName;
    this.swigValue = swigValue;
    swigNext = swigValue+1;
  }

  private TelioResult(String swigName, TelioResult swigEnum) {
    this.swigName = swigName;
    this.swigValue = swigEnum.swigValue;
    swigNext = this.swigValue+1;
  }

  private static TelioResult[] swigValues = { RES_OK, RES_ERROR, RES_INVALID_KEY, RES_BAD_CONFIG, RES_LOCK_ERROR, RES_INVALID_STRING, RES_ALREADY_STARTED };
  private static int swigNext = 0;
  private final int swigValue;
  private final String swigName;
}

