#!/usr/bin/env bash
set -euxo pipefail

# This forces export of needed binding for Java
LINKER=$(basename $0)
LINKER=${LINKER#"d-"}
ARGS=$@

while (( "$#" )); do
	if [[ $1 == *"-Wl,--version-script="* ]]; then
		VERSION=${1#"-Wl,--version-script="}
		SED_ARGS='s/global:/global:\n    Java*;\n    JNI_OnLoad;\n/'
		if [ "$(uname)" != "Darwin" ]; then
			sed -i "$SED_ARGS" "$VERSION"
		else
			sed -i '' "$SED_ARGS" "$VERSION"
		fi
		break
	fi

	shift
done

exec $LINKER $ARGS
