name: Benchmarks
on: [workflow_call]
permissions: {}

jobs:
  telio-firewall:
      runs-on: ubuntu-22.04
      steps:
        - uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7
        - name: Telio firewall benchmarks
          working-directory: crates/telio-firewall
          run: cargo bench --features test_utils --bench firewall_bench "64" -- --warm-up-time 1 --measurement-time 1
