name: Benchmarks
on: [workflow_call]
permissions: {}

jobs:
  telio-firewall:
      runs-on: ubuntu-22.04
      steps:
        - uses: actions/checkout@0ad4b8fadaa221de15dcec353f45205ec38ea70b # v4.1.4
        - name: Telio firewall benchmarks
          working-directory: crates/telio-firewall
          run: cargo bench --features test_utils --bench firewall_bench "64" -- --warm-up-time 1 --measurement-time 1
