name: Tests
on: [workflow_call]
permissions: {}

jobs:
  coverage-linux:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@a5ac7e51b41094c92402da3b24376905380afc29 # v4.1.6
      - name: Install stable toolchain
        uses: actions-rs/toolchain@b2417cde72dcf67f306c0ae8e0828a81bf0b189f # v1.0.6
      - name: Download tarpaulin
        run: curl -L 'https://github.com/xd009642/tarpaulin/releases/download/0.27.1/cargo-tarpaulin-x86_64-unknown-linux-musl.tar.gz' | tar xvz
      - name: Verify download
        run: echo '564ea439a14eced45cdb3e50b55a463502d9fbfb7722535c5d0390b6577ce343  cargo-tarpaulin' | sha256sum --check --status
      - name: Run cargo-tarpaulin
        run: sudo -E env "PATH=$PATH:/home/runner/.cargo" ./cargo-tarpaulin -v --all --out Xml --offline --exclude-files '../3rd-party/*,clis/*'
