name: Definition of Done
on:
  pull_request:
    types: [opened, edited]
permissions: {}

jobs:
  check-dod:
    permissions:
      pull-requests: write
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@9bb56186c3b09b4f86b1c65136769dd318469633 # v4.1.2
      - name: Check DoD
        uses: platisd/definition-of-done@99622dd6e4480530c0c6c571651b58d3283583b4 # v2.0.0
        with:
          dod_yaml: 'dod.yml'
          github_token: ${{ secrets.GITHUB_TOKEN }}
