name: Definition of Done
on:
  pull_request:
    types: [opened, edited]
permissions: {}

jobs:
  check-dod:
    permissions:
      pull-requests: write
    runs-on: ubuntu-20.04
    # Excluding Dependabot PRs from this check.
    if: github.actor != 'dependabot[bot]'
    steps:
      - uses: actions/checkout@0ad4b8fadaa221de15dcec353f45205ec38ea70b # v4.1.4
      - name: Check DoD
        uses: platisd/definition-of-done@e69d712b88c93ef88a73da4435155a0054b7df5e # v2.2.0
        with:
          dod_yaml: 'dod.yml'
          github_token: ${{ secrets.GITHUB_TOKEN }}
