name: Definition of Done
on:
  pull_request:
    types: [opened, edited, synchronize]
  merge_group:
    types: checks_requested
permissions: {}

jobs:
  check-dod:
    permissions:
      pull-requests: write
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - name: Check DoD
        # Excluding Dependabot PRs and merge_group events from this check.
        if: github.event_name == 'pull_request' && github.actor != 'dependabot[bot]'
        uses: platisd/definition-of-done@e69d712b88c93ef88a73da4435155a0054b7df5e # v2.2.0
        with:
          dod_yaml: 'dod.yml'
          github_token: ${{ secrets.GITHUB_TOKEN }}
