name: Definition of Done
on:
  pull_request:
    types: [opened, edited]
permissions: {}

jobs:
  check-dod:
    permissions:
      pull-requests: write
    runs-on: ubuntu-20.04
    # Excluding Dependabot PRs from this check.
    if: github.actor != 'dependabot[bot]'
    steps:
      - uses: actions/checkout@c85c95e3d7251135ab7dc9ce3241c5835cc595a9 # v3.5.3
      - name: Check DoD
        uses: platisd/definition-of-done@99622dd6e4480530c0c6c571651b58d3283583b4 # v2.0.0
        with:
          dod_yaml: 'dod.yml'
          github_token: ${{ secrets.GITHUB_TOKEN }}
