name: Wireguard-go version update check
on: [pull_request]
permissions: {}

jobs:
  wireguard-go-version-update-check:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@c85c95e3d7251135ab7dc9ce3241c5835cc595a9 # v3.5.3
        with:
          fetch-depth: 0
      - run: |
          WG_GO_CHANGED=$(git diff --name-only ${{ github.event.pull_request.base.sha }}..${{ github.event.pull_request.head.sha }} | grep wireguard-go-rust-wrapper/wireguard-go/ | wc -l)
          if [ $WG_GO_CHANGED -gt 0 ]
          then
            echo Wireguard-go source code updated
            WG_GO_VERSION_UPDATED=$(git diff ${{ github.event.pull_request.base.sha }}..${{ github.event.pull_request.head.sha }} -- wireguard-go-rust-wrapper/wireguard-go/main.go | grep "+func wg_go_version_" | wc -l)
            if [ $WG_GO_VERSION_UPDATED -eq 0 ]
            then
              echo Wireguard-go source has changed but wg_go_version_x_y_z seems to be not updated
              exit 1
            fi
          fi
